### ISSUE TITLE
ParseError when encountering `yield of()`

### ISSUE THREAD

**Issue by eps1lon** [facebook/hermes#1028]
## Bug Description

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: RN 0.71.7 and https://hermesengine.dev/playground/
React Native version (if any): 0.71.7
OS version (if any): any
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): any

## Steps To Reproduce

1. transpile and minify code for production (e.g. with Terser)
2. end up with `yield of()`

code example:

```js
function of() {}
function* foo() {
    yield of()
}
```

## The Expected Behavior

No parse error

**Comment by avp** [comment]
Thanks for the report, we'll look into fixing this.

**Comment by eps1lon** [comment]
@avp Does mangling of variable/function names even make sense if we use Hermes to produce byte code? It shouldn't have a noticeable difference for the size of the bytecode and even less of an impact for startup perf, no? That would at least unblock us because we have little control over the mangled names that are produced but we could just tell people "don't write `yield of` for now".

**Comment by avp** [comment]
Variable names aren't stored in production bytecode bundles. Function names might be, depending on how you've compiled your JS, because you might want to use the `.name` property on the function at some point. We do provide a flag `-fstrip-function-names` which will remove all the function names and replace them with `'function-name-stripped'`, which you can do if you are completely sure you don't want the function names to be available at runtime.

Another way to get unblocked while causing less disruption is to put `of` in the "reserved" list passed to terser e.g. on the CLI here: https://github.com/terser/terser#cli-mangle-options - most minifiers should support similar options.

Hopefully one of those options works until the bug is fixed for you.

**Comment by tmikov** [comment]
@eps1lon Our position is (and always has been) that source minification should not be used with Hermes. If cases are discovered where it can be demonstrated that minification actually improves the compiled bytecode meaningfully (size, perf, etc), we will address them. In practice it seems that Hermes users overwhelmingly use minification, simply because that is the default in the RN build pipeline (AFAICT).

**Comment by eps1lon** [comment]
> Another way to get unblocked while causing less disruption is to put of in the "reserved" list passed to terser e.g. on the CLI here: [terser/terser#cli-mangle-options](https://github.com/terser/terser#cli-mangle-options) - most minifiers should support similar options.

How I understood it, that option only considers the names of **input** names i.e. it wouldn't mangle `of`. But we want to control the output i.e. control that it doesn't **produce** `of`. Which is not possible AFAICT without forking Terser's default `nth_identifier`.

> Our position is (and always has been) that source minification should not be used with Hermes.

That makes sense to me, thanks for confirming. We'll just stop mangling but keep applying Terser since that also inlines certain function calls and other optimizations.

**Comment by eps1lon** [comment]
@tmikov Is this fixed or did you mean to close this as "not planned"? It still reproduces in the Hermes playground.

**Comment by tmikov** [comment]
@eps1lon the example parses with the latest version of Hermes without an error.
