### ISSUE TITLE
Hermes is not enabled in Android Native Files

### ISSUE THREAD

**Issue by lemanrs** [facebook/hermes#1189]
I am trying to expo publish my Android app and am getting the following error:

**In app.json: Hermes is enabled In Android native project: Hermes is not enabled(gradle.properties&app/build.gradle)**

I have the following code in the android native files(react-native0.72.1) https://react-native-community.github.io/upgrade-helper/?from=0.69.7&to=0.72.1:

```
//gradle.properties
hermesEnabled=true

//app/build.gradle
if (hermesEnabled.toBoolean()) {
      implementation("com.facebook.react:hermes-android")
 }
```

Am I missing any other code to enable hermes in android?

**Comment by mattbfb** [comment]
This repository is for the Hermes engine itself, whereas I believe your issue is with the configuration of Expo or React Native. You may find more answers with an issue in the Expo repository (https://github.com/expo/expo) or React Native (https://github.com/facebook/react-native), depending on which framework controls the specific build files you're editing.
