### ISSUE TITLE
Hermes should throw an exception when Maxium BigInt size exceed

### ISSUE THREAD

**Issue by JimWongM** [facebook/hermes#1213]
## Bug Description

Hermes should throw an exception when Maxium BigInt size exceed, but it did not because of Dead Code Elimination.

```CallBuiltinInst [HermesBuiltin.exponentiationOperator]``` is Eliminated by DCE and does not throw an exception. This optimization changes the semantics of JavaSript program.

The problem may be related to the side effect of BigInt for ExponentiationKind.

Hermes version: ebf7889c4f7f944630caed4abfebe49ee90f691a (latest version)
OS version (if any): Linux, MacOS

## Steps To Reproduce

1. Build latest hermes
2. ./hermes -O test.js
3. ./hermes -O0 test.js

code example:
test.js
```
function main() {
    const v1 = -649410151n * -649410151n;
    try {
      9007199254740992n ** v1;
      print("hello");
    } catch (e4) {print(e4)}
  }
  main();
```

## The Expected Behavior

The result of step 2 and step 3 is different. In full optimization level, Hermes shoud throw an exception "RangeError: Maximum BigInt size exceeded".

**Comment by tmikov** [comment]
Thanks for reporting this. It is an intriguing case, because fixing it would mean that we wouldn't be able to eliminate any dead code dealing with unknown bigints.

The way we think about this is that "RangeError: Maximum BigInt size exceeded" is unpredictable and cannot be relied on; it is conceptually similar to an OOM. So, the optimizer should be allowed to eliminate it.

Similarly the optimizer is allowed to eliminate the dead code that performs allocations, even though that code could theoretically cause an OOM at runtime.
