### ISSUE TITLE
Support for import/export at runtime

### ISSUE THREAD

**Issue by verenkoska** [facebook/hermes#1382]
## Problem
When executing any code involving import/export at runtime, I get the following error:

`'import' statement requires module mode`

Is there any way to support it at runtime? 
I was also thinking of binding a C++ code as a workaround, but I would need the same import syntax.

Thank you!

**Comment by tmikov** [comment]
The Hermes parser supports the syntax, but the Hermes runtime does not currently have a supported implementation of ESM (ES6 modules). 

The main reason is that React Native relies on bundler (usually Metro) which provides its own non-standard implementation of ESM, with various customizations, so the Hermes implementation would not even be used.

This is unfortunate, because built-in support of ESM provides opportunities for a number of important optimizations (like inter-module inlining). Static Hermes will eventually provide ESM, but as of now it still doesn't either.

**Comment by trossimel-sc** [comment]
Thanks for the fast response @tmikov ! This is unfortunate
And what about commonjs syntax? It also seems to work with -commonjs flag but not when using JSI

**Comment by verenkoska** [comment]
Thanks for the fast response @tmikov ! This is unfortunate
And what about commonjs syntax? It also seems to work with -commonjs flag but not when using JSI

**Comment by tmikov** [comment]
JSI is an API to access the VM at runtime, it is orthogonal to this. Hermes does ship with a runtime implementation of commonjs, but it is unsupported and we don't recommend using it.

**Comment by 0x80** [comment]
If there is an open issue somewhere about ESM support that I can subscribe to, I'd love to hear about it.

**Comment by tmikov** [comment]
@0x80 there is no separate issue for it. We generally use issues to track new unknown bugs, not as a way to plan our own work (I realize this may not be ideal).

Unfortunately, as I mentioned above, the main reason that this hasn't been much of a priority for us is that all existing users of Hermes rely on various build pipelines and specifically on JS bundlers like Metro. They would have to alter their build pipelines in fundamental ways. So, we are not in a hurry to work on something that will be unused.

To be clear: Hermes already **had** a built-in implementation of require() and import/export **for years** and  **no one ever used it**. We deactivated it because after so many years of inactivity it was effectively unsupported. We don't want a repeat of that.

With all that said, we still need to do this. There are a couple of major reasons:
- builtin import/export allow us to perform static optimizations across modules.
- builtin import/export is required for good support of top level `await`.

This time we will do it incrementally and coordinate at the very least with the Metro bundler.


However

**Comment by 0x80** [comment]
@tmikov Thanks for explaining. I realized now that my desire for ESM support is much simpler than what this issue suggested. I happened to post it here because other related ESM issues were also closed and I thought it was related. My issue has to do with the bundler not interpreting the package.json `exports` field correctly, so that would be for Metro and not Hermes...
