### ISSUE TITLE
runtime cann't execute in std::Thread 

### ISSUE THREAD

**Issue by scorpionfeng** [facebook/hermes#1396]
when use the code such as below in:

...
Thread t1([&runTime,argument,resolver](https://github.com/margelo/react-native-worklets-core/issues/193){
argument.asObject(runtime).asFunction(runtime).call(runtime,nullptr,0)// this line will crash
}).deteach()

Is there any other approach to fix the crash ?

**Comment by neildhar** [comment]
Hey @scorpionfeng, there is nothing that prevents you from running Hermes on a newly spawned thread. However,  you need to ensure that access to the runtime is properly synchronised. For instance, you could guard access to the runtime with a mutex, in order to ensure that it isn't simultaneously accessed from multiple threads. Hermes does not support having multiple threads call into the same runtime at the same time, and that is likely why you are observing a crash.

**Comment by scorpionfeng** [comment]
and  if I want to use runtime in the thread ,  shall I create a new runtime use api: facebok::hermes::makeHermesRuntime() ,is that correct?
