### ISSUE TITLE
Issue Title: Error installing FBLazyVector during pod install

### ISSUE THREAD

**Issue by Joselo-zn** [facebook/hermes#1433]
Description:

I'm encountering an issue while trying to install the FBLazyVector pod as a dependency for Hermes in my React Native macOS project. The error occurs when pod install --repo-update tries to clone the specific branch v0.73.30 from the React Native GitHub repository, which does not seem to exist.

Details:

When running pod install --repo-update, the following error is encountered:

Fetching podspec for `hermes-engine` from `../node_modules/react-native-macos/third-party-podspecs/hermes-engine.podspec`
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.73.30)

[!] Error installing FBLazyVector
[!] /usr/bin/git clone https://github.com/facebook/react-native.git /var/folders/22/669fc4xj0bg9ts3rf8g_cnc00000gn/T/d20240609-72424-xvlwsc --template= --single-branch --depth 1 --branch v0.73.30

Cloning into '/var/folders/22/669fc4xj0bg9ts3rf8g_cnc00000gn/T/d20240609-72424-xvlwsc'...
warning: Could not find remote branch v0.73.30 to clone.
fatal: Remote branch v0.73.30 not found in upstream origin

Steps to Reproduce:

Add hermes-engine as a dependency in your Podfile:

pod 'hermes-engine', :podspec => '../node_modules/react-native-macos/third-party-podspecs/hermes-engine.podspec'
Run the following commands:

sh
cd macos
rm -rf Pods Podfile.lock
pod install --repo-update
Observe the error during the installation of FBLazyVector.

Expected Behavior:
The pod install --repo-update command should successfully install all the dependencies without errors.

Actual Behavior:
The command fails to install FBLazyVector due to the missing branch v0.73.30 in the React Native GitHub repository.

Environment:
macOS version: 14.5 (23F79)
Xcode version: 15.4 (15F31d)
React Native version: 0.73.30
Hermes version: 12
CocoaPods version: 1.15.2
Node version: V18.18.2

Additional Information:
The issue seems to be that the specified branch V0.73.30 does not exist in the React Native GitHub repository. This is preventing the successful installation of the necessary pod.

Is there an alternative solution to this problem?

Thank you for your assistance.

**Comment by tmikov** [comment]
Hi, Hermes does not have a dependency on either DoubleConversion or FBLazyVector. In fact, Hermes by design has no dependencies.

You seem to be having a problem with a Pod file that is not a part of the Hermes project - `react-native-macos/third-party-podspecs/hermes-engine.podspec`. Further, you seem to be referring to https://github.com/microsoft/react-native-macos, which is a fork of React Native by Microsoft (they also have their own fork of Hermes). 

Unfortunately we can't help you with either of these. I suggest filing an issue with `https://github.com/microsoft/react-native-macos`, or if you can reproduce the problem with `https://github.com/facebook/react-native`, filing an issue there.
