### ISSUE TITLE
SyntaxError: Invalid RegExp: Invalid escape, js engine: hermes

### ISSUE THREAD

**Issue by Albert-Gao** [facebook/hermes#1460]
## Bug Description

a regexp from a library [zod-to-json-schema](https://github.com/StefanTerdell/zod-to-json-schema) triggers this error on Hermes.

![image](https://github.com/user-attachments/assets/71af5341-80aa-4e74-8816-47ad3ba36ae8)

- "expo": "~51.0.21",
- "react-native": "0.74.3"

## Steps To Reproduce

a repo to reproduce it.

https://github.com/Albert-Gao/rn-invalid-regexp

## The Expected Behavior

It should work. (Works on JSC)

## More

Is it related to this?
https://github.com/facebook/hermes/issues/1027

Also created an issue on the lib side to see if we can update this regexp, if it is hard to solve on an engine level.
https://github.com/StefanTerdell/zod-to-json-schema/issues/129

**Comment by tmikov** [comment]
Can you please provide a minimal repro of the regexp for the Hermes CLI. Ideally it should be one line. We are not able to test RN apps.

**Comment by Albert-Gao** [comment]
sure :)

I found a test here:
`https://github.com/facebook/hermes/blob/main/test/hermes/regexp-icase.js`

the regexp causing problem is this one:
`RegExp("^(\\p{Extended_Pictographic}|\\p{Emoji_Component})+$", "u")`

should i just put it in the test like that, because it fails on the initialization? so it is suffice as a test case?

**Comment by neildhar** [comment]
Hey @Albert-Gao, that feature has been implemented in trunk in https://github.com/facebook/hermes/pull/1295, but isn't yet in the latest version of React Native. It should work when the next version of RN becomes available.

In the interim, if you have static RegExps that use this feature, you can consider using this babel transform: https://babeljs.io/docs/babel-plugin-transform-unicode-property-regex

Note that if you are using the babel transform, you will need to write your RegExp in the style `/^(\\p{Extended_Pictographic}|\\p{Emoji_Component})+$/u`, instead of invoking `new RegExp`
