### ISSUE TITLE
RN@0.75.2 app build for Mac Catalyst fails with: `hermes.framework: bundle format is ambiguous (could be app or framework)`

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/hermes#1492]
Hey, I am migrating my libraries / app from RN@0.74 to the latest RN@0.75.2. When building for Mac Catalyst target my build fails with that error `hermes.framework: bundle format is ambiguous (could be app or framework)`. I did a brief googling, and it seems the issue should be on Hermes side, something not packed correctly for the distribution? Or is it a problem elsewhere?

**Comment by tmikov** [comment]
Based on your description and after reviewing the details, it’s important to clarify that Hermes itself does not provide a binary artifact. This means that the issue you're seeing is unlikely to be caused directly by Hermes.

The error message you're encountering—"bundle format is ambiguous (could be app or framework)"—could potentially be related to how the build system or the React Native configuration is handling the packaging process, rather than an issue with Hermes. 

If you have further details or logs that might help in diagnosing the issue, please feel free to share them. Alternatively, you might find more insights by discussing this in the React Native community, as they might have encountered similar issues during migrations.

**Comment by birdofpreyru** [comment]
Thanks @tmikov , I'll move the issue to RN repo then :)
