### ISSUE TITLE
shermes warns that STDIN is an undeclared variable

### ISSUE THREAD

**Issue by guest271314** [facebook/hermes#1585]
## Bug Description

Since `hermes` and `shermes` don't have any capability to read standard input I'm trying to use the FFI example to read stdin. 

```
build_release/bin/shermes -version
LLVM (http://llvm.org/):
  LLVH version 8.0.0svn
  Optimized build

Static Hermes JS Compiler v0.0
```

## Steps To Reproduce

Modify https://github.com/facebook/hermes/tree/static_h/examples/ffi to read `/dev/stdin`

```
    let f = fopen("/dev/stdin", "r");
    try {
        print("====");
        print(freadAll(f));
        print("====");
    } finally {
        fclose(f);
    }
```

```
printf "%s" "a" | build_release/bin/shermes -v -typed -exec hermes-static_h/examples/ffi/fopen.js -
```

prints

```
<stdin>:1:1: warning: the variable "a" was not declared in anonymous function
a
^
```

## The Expected Behavior

No warnings. The capability to read STDIN with the FFI implementation.

**Comment by tmikov** [comment]
The `shermes` compiler combines all source files passed onto the command line and compiles them together. You are passing two files `hermes-static_h/examples/ffi/fopen.js` and `-`. The `shermes` compiler reads the contents of `-` from stdin. The contents are `a`, which you are supplying.

So, `shermes` compiles `fopen.js` concatenated` with `a`, which causes a compilation warning, since `a` is an undeclared variable.

If you want to pass data to stdin, you shouldn't also pass the `-` parameter.

Or you could compile into a binary, and then run that binary like any other, including redirect data into stdin.
