### ISSUE TITLE
how to cross-compile hermes with a custom toolchain

### ISSUE THREAD

**Issue by georged-youi** [facebook/hermes#162]
Hi,

I'm trying to build hermes for a linux target that's using this toolchain: https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/arm-linux-gnueabi/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabi.tar.xz

Is there a doc describing how to compile hermes with a custom toolchain?

**Comment by mhorowitz** [comment]
Hi, thanks for your question.
We don't have a doc which explains this specifically, but I can give you a few pointers to get you started.  https://github.com/facebook/hermes/blob/master/doc/BuildingAndRunning.md#building-on-linux-and-macos documents how to build using the typical mechanism.  The real underlying build is CMake and ninja-based, and these python scripts are mostly simple wrappers to pass the correct CMake flags.  https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling documents CMake's cross-compilation support.  The example at https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-linux seems to be for some version of linaro, so hopefully that can help get you started.  Together, this should be enough for you to work out how to invoke cmake in order to cross-compile Hermes for your environment.
I hope this helps!
