### ISSUE TITLE
How can I add I/O?

### ISSUE THREAD

**Issue by TheSalarKhan** [facebook/hermes#174]
I am sorry. This might seem a very basic question but, I have downloaded the project, I have followed the build instructions and I have the hermes artifacts built, including hvm hermes-repl. 

I wanted to research on using hermes for an edge computing usecase, and I wanted to add basic functionality to it. To be specific some IO. Can someone point me to a resource that shows me how? So far this is what I have got
```
$: ./hermes-repl 
>> print("asdf");
asdf
undefined
>> import { func } from "./module";
SyntaxError: 1:1:'import' statement requires module mode
    at eval (native)
    at evaluateLine (JavaScript:1:4939)
>> 

```

I can't find documentation so I'm kinda stuck.

Thanks!

**Comment by mhorowitz** [comment]
Thanks for your question.

There are two possible answers, depending on how you want to approach this.

The literal answer to your question is that Hermes does not have any native support for I/O.  However, Hermes has APIs you can use to call C++ code from JavaScript.  You can see some examples of HostFunction in the test suite [here](https://github.com/facebook/hermes/blob/master/API/jsi/jsi/test/testlib.cpp#L600).  You could use that to add a function to do whatever I/O you need for your application.  This [comment](https://github.com/facebook/hermes/issues/43) references the hermes-jsi tool, which might be a good starting point.

Since your question includes an import, I wonder if you were hoping to use NodeJS's fs module to do I/O.  Hermes has no support for using Node modules, so that won't work.

For completeness, I wanted to point out that we do have support for JS imports, but it is mainly used when compiling a number of JS files together and supporting modularity, so it's not supported by the repl.  In any case, modules aren't going to help you do I/O, as JS modularity isn't going to allow you to extend the native functionality of the JS engine.
