### ISSUE TITLE
TypeError: undefined is not a function, js engine: hermes

### ISSUE THREAD

**Issue by asavardplante** [facebook/hermes#199]
### BUG
Hey guys, here's my problem. I'm reading the `nativeEvent` value from the `onChange` props and using the text from it to show it to the user. When using Hermes in my project, the app crashes immediately when I enter a string in my `TextInput`.
***
Something strange that I found is when I'm in debug mode, the app doesn't crash and I can actually see what text's value is when I enter something in my `TextInput` and if I log it right after.

### CODE IMPLICATED
```   
  onChange({ text }) {
    const { onFocus } = this.props;
    const newText = text.trimStart();

    //do other thing
   ...
  }

<TextInput
    onChange={(t) => this.onChange(t.nativeEvent)}
>
```

**Comment by mhorowitz** [comment]
@asavardplante When you saw the TypeError in the title, did it also give you a line number and column number?  That would help be certain what the problem is.

I suspect that the error is coming from `text.trimStart()`, as it isn't in older versions of Hermes.  (It is in Hermes 0.4.0, but that isn't compatible with the current release of React Native.  It will be the default when RN 0.62 is released.)  You can try using `text.trimLeft()` instead, which is the older name for this function.

I'm not sure why RN doesn't provide a polyfill for `trimStart`.  That would be a question for the React Native folks, as they provide the polyfills.

**Comment by asavardplante** [comment]
@mhorowitz Thanks, it worked for us !
