### ISSUE TITLE
Include benchmarks in README

### ISSUE THREAD

**Issue by AliFlux** [facebook/hermes#22]
Hi.
Wouldn't it be great if the benchmarks were included in the README? In a simple tabular format similar to [this](https://github.com/necolas/react-native-web/tree/master/packages/benchmarks#example-results).

**Comment by LifeIsStrange** [comment]
Yet another js compiler? All this effort could have been better allocated for improving v8 startup time and performance instead of reinventing the wheel.
Showing honest benchmarck would prove or disprove that you are victim or not of the NIH syndrome.
https://en.m.wikipedia.org/wiki/Not_invented_here

**Comment by kesha-antonov** [comment]
Here's their presentation with some numbers
Chain React 2019: Hermes Engine Announcement
https://www.youtube.com/watch?v=zEjqDWqeDdg

**Comment by nes123** [comment]
I didnt see any change to the APK size. Didnt check the other parameters yet but the feeling is that it is not faster than before. What is your experience?

**Comment by kesha-antonov** [comment]
Hmm
I didn't try yet. Interested too
