### ISSUE TITLE
Plans for supporting with statement

### ISSUE THREAD

**Issue by swabbass** [facebook/hermes#222]
Thx for the great and fast engine so far we have good results 

we are using in our app lodash and I think it is being used by a lot of devs and part of it like `template` function and maybe other functions uses `with(obj)` block so do you guys have plan to support it in the future ? maybe a hint maybe a way to write our own with implementation? 

other question is can I use hermes 0.5.0 with rn62? since it is written in the release notes that its for rn63
big Thanks for the effort

**Comment by tmikov** [comment]
Hi, supporting the "with" statement hasn't been a priority for us since we don't use it internally, and it is deprecated and generally not recommended. With that said, we are discussing whether we may be able to add it sooner, if it doesn't require a lot of effort. I will post an update here.

In the meantime, are you able to use this workaround: https://github.com/lodash/lodash/issues/3709#issuecomment-375898111 ?

Re Hermes 0.5.0: it is only compatible with RN 0.63.

**Comment by swabbass** [comment]
> Hi, supporting the "with" statement hasn't been a priority for us since we don't use it internally, and it is deprecated and generally not recommended. With that said, we are discussing whether we may be able to add it sooner, if it doesn't require a lot of effort. I will post an update here.
> 
> In the meantime, are you able to use this workaround: [lodash/lodash#3709 (comment)](https://github.com/lodash/lodash/issues/3709#issuecomment-375898111) ?
> 
> Re Hermes 0.5.0: it is only compatible with RN 0.63.

THX for the awsome answer

**Comment by tmikov** [comment]
Merging into duplicate https://github.com/facebook/hermes/issues/1056 

(yes, it is counter-intuitive to merge into the later issue, but it is convenient in this case).
