### ISSUE TITLE
Building assemble release through command line showing warnings

### ISSUE THREAD

**Issue by Kailash23** [facebook/hermes#256]
I enabled Hermes engine in my app, everything is working fine except I am getting warnings while generating assemble release of the application using the command `./gradlew assembleRelease`.

[Click to see logs1](https://hastebin.com/ehefikuyag.coffeescript)
[Click to see logs2](https://hastebin.com/apokafacal.coffeescript)

Please let me know what could be the possible solution to fix the warning.

**Comment by mhorowitz** [comment]
The pastes look like minified JS.  I don't see any warnings in them.

Can you be more specific about exactly which warnings you are seeing and would like to fix?

**Comment by Kailash23** [comment]
These are the warnings you can see them in the log2 file. 
 [warnings](https://hastebin.com/uborumimof.coffeescript)

Right now after enabling Hermes, I am getting these logs while running the app in debug mode using the command `react-native run-android`. This is not happening every time, getting these logs only in the first run.
 [logs](https://hastebin.com/yoyoyusepu.coffeescript)

This doesn't seem like normal logs. So I thought I should ask, although the app is running fine in both debug and assemble release.
Let me know if there is more info required. Thanks :)

**Comment by mhorowitz** [comment]
Ah, I didn't scroll down past all the whitespace to see the errors.  Sorry about that.

Those warnings come from React Native JavaScript code: https://github.com/facebook/react-native/blob/master/Libraries/Network/fetch.js

This happens because that code references some symbols as globals, and Hermes does not include them in its list of standard JavaScript global properties.  An earlier polyfill does define these, but in strict mode, use of unknown globals causes a warning to be emitted which you see here.

If you want to just disable warning generation, you can follow the instructions here https://github.com/facebook/hermes/issues/216#issuecomment-615429942

If you like, you could also report the underlying bug to the React Native team so they can fix it.
