### ISSUE TITLE
Redeclaration of a function* inside a block definition

### ISSUE THREAD

**Issue by igor-simoes** [facebook/hermes#265]
Hi everyone,
I found a case of redeclaration of a generator function inside a block definition.

version: 0.5.0
OS: Linux Mint 19.2 x64

steps to reproduce:
```
{ 
    function* f() { yield 1 }
    function f() { print(2) }
}
f()
```
Actual results:
2

Expected results:
SyntaxError: Identifier 'f' has already been declared

V8, SpiderMonkey works as expected.

cinfuzz

**Comment by avp** [comment]
This is due to the fact that Hermes doesn't support block scoping yet - we're actively working on adding support for block scoping and `let`/`const`. If you remove the braces surrounding the function declarations, then the resultant code would be valid. That's what Hermes currently has implemented. 

See [this document](https://github.com/facebook/hermes/blob/master/doc/Features.md) for information on what language features Hermes supports.

**Comment by igor-simoes** [comment]
Ok, thanks.
