### ISSUE TITLE
Hermes CLI doesn't display that a script terminated with an exception

### ISSUE THREAD

**Issue by igor-simoes** [facebook/hermes#266]
Hi everyone,
I found this case of a throw statement that should throws an object exception. Hermes returns the object without throw the exception.

version: 0.5.0
OS: Linux Mint 19.2 x64

steps to reproduce:
```
throw { message: "Error" }
```

Actual results:
```
[object Object]
```

Expected results:
```
(spidermonkey)
uncaught exception: [object Object]

(V8)
[object Object]
throw { message: "Error" }
^
```

V8, SpiderMonkey, Chakra and JSC works as expected.

cinfuzz

**Comment by tmikov** [comment]
Hermes behaves correctly. It can be seen clearly in this test:
```
try {
    throw { message: "Error" }
} catch (e) {
    print("caught", e);
}
```

The problem is that the we are not printing any information saying that there was an exception. See https://github.com/facebook/hermes/blob/dada486025ce28eebcbb21cdadbc9e1e4dae4ea1/lib/VM/Runtime.cpp#L1015 .

This should be easy to fix by just adding some static text like "Exception:" before printing the rest. PRs welcome.
