### ISSUE TITLE
Invalid escape sequence with a non-octal-eight

### ISSUE THREAD

**Issue by igor-simoes** [facebook/hermes#267]
Hi everyone,
maybe is a case of an invalid numeric escape (non-octal-eight) in strict mode, but the same occurs using the strict mode and without it. Is this an expected behavior of Hermes? (implementation-dependent)

version: 0.5.0
OS: Linux Mint 19.2 x64

Steps to reproduce:
```
print(`\8`);
```
Actual results:
```
SyntaxError: untagged template literal contains invalid escape sequence
```
Expected results:
```
8
```
The same occurs in strict mode
```
"use strict";
print(`\8`);
```

V8, SpiderMonkey, Chakra works as expected.

cinfuzz

**Comment by avp** [comment]
This is throwing a SyntaxError due to the [static semantics](https://tc39.es/ecma262//#sec-static-semantics-template-early-errors) for template literals.

The [NotEscapeSequence](https://tc39.es/ecma262//#prod-NotEscapeSequence) is being matched due to "DecimalDigit but not `0`" being used, and you've constructed a NoSubstitutionTemplate which is not tagged.

As you said, `8` is not an octal literal, so section [B.1.2](https://tc39.es/ecma262//#sec-additional-syntax-string-literals) doesn't appear to apply either.

It's possible I'm missing some part of the spec that's being used to explicitly allow `8` to be used as an escape sequence here, so if anyone else can explain the intended behavior, that would be helpful.

**Comment by avp** [comment]
See https://github.com/tc39/test262/issues/2653 for other discussion of this issue.
