### ISSUE TITLE
Cannot read property `prototype` of undefined for function definition

### ISSUE THREAD

**Issue by pke** [facebook/hermes#272]
It seems hermes can not compile this JS code correctly from the HTML-to-Markdown package https://github.com/domchristie/turndown:

```js
function createHTMLParser () {
  var Parser = function () {};

  {
    var JSDOM = require('jsdom').JSDOM;
    Parser.prototype.parseFromString = function (string) {
      return new JSDOM(string).window.document
    };
  }
  return Parser
}
```

It complains that `Parser` is undefined.

![image](https://user-images.githubusercontent.com/164625/84842139-aa523380-b044-11ea-80a5-398132839d91.png)

**Comment by Huxpro** [comment]
Hi @pke, would you able to reduce the code to a minimal reproducible?
I tried to follow your intention and ended up with

```js
var Parser = function () {};
Parser.prototype.parseFromString = function () { return 0 } 
Parser.parseFromString() // from your stack trace
```

But this is problematic on its own because `P` really doesn't have `parseFromString()` on it. You would need to create an instance like `new Parser().parseFromString` to access methods defined in `Parser.prototype`.

**Comment by Huxpro** [comment]
A side note to Hermes members: __but we need to improve our error message__

```js
// proto.js
var P = function () {};
P.prototype.p = function () { print("p") }
P.p();
```

```
λ eshost proto.js
#### Hermes

TypeError: undefined is not a function

#### JavaScriptCore

TypeError: P.p is not a function. (In 'P.p()', 'P.p' is undefined)

#### SpiderMonkey

TypeError: P.p is not a function

#### V8

TypeError: P.p is not a function
```
