### ISSUE TITLE
ReferenceError: Property Object__DO_NOT_TRANSFORM doesn't exist

### ISSUE THREAD

**Issue by likern** [facebook/hermes#280]
As I've switched to using Hermes I started seeing this error right after running application.
Before I never had this kind of error and I suggest it's related to Hermes engine.

![photo5467896188951965879](https://user-images.githubusercontent.com/842306/86250903-de3b6600-bbb9-11ea-8c54-940c3f509ffb.jpg)

Source code where error happens:
```tsx
interface SvgCircleProps {
  color: string;
}

const SvgCircle = ({ color, ...otherProps }: SvgCircleProps) => (
  <Svg width={8} height={8} viewBox='0 0 8 8' fill='none' {...otherProps}> // THIS LINE
    <Circle cx={4} cy={4} r={4} fill={color} />
  </Svg>
);
```

**SvgCircle** is called through Pagination component with css-prop transformation:
```tsx
export const Pagination = ({ screens, index, style }: PaginationProps) => {
  assert(screens >= 0, 'screens is negative number');
  assert(index >= 0 && index < screens, 'activeScreen is out of range');

  return (
    <View
      css={`
        flex-direction: row;
        justify-content: center;
      `}
      style={style}
    >
      {Array.from(Array(screens).keys()).map(value => (
        <SvgCircle
          css={`
            margin-right: ${value + 1 === screens ? 0 : 12}px;
          `}
          key={value}
          color={value === index ? '#2D9AFC' : '#E0E6EB'}
        />
      ))}
    </View>
  );
};
```

Hermes: enabled, default
React Native Version: 0.62.2

@msand Can it be related to react-native-svg?
@styled-components Can it be related to styled-components?

**Comment by likern** [comment]
If I pass through style object (to which `css` property is transformed to) the exception is gone.

```tsx
interface SvgCircleProps {
  color: string;
  style?: StyleProp<ViewStyle>;
}

const SvgCircle = ({ color, style, ...otherProps }: SvgCircleProps) => (
  <Svg width={8} height={8} viewBox='0 0 8 8' fill='none' {...otherProps}>
    <Circle cx={4} cy={4} r={4} fill={color} />
  </Svg>
);
```

If I try to use this style object - the error comes back
```tsx
const SvgCircle = ({ color, style, ...otherProps }: SvgCircleProps) => (
  <Svg width={8} height={8} viewBox='0 0 8 8' fill='none' style={style} {...otherProps}>
    <Circle cx={4} cy={4} r={4} fill={color} />
  </Svg>
);
```

**Comment by mhorowitz** [comment]
Thanks for the detailed bug report!  It's a bit hard to say what's going on here because Hermes doesn't consume typescript or JSX directly.  These are transformed to JavaScript, most likely using Babel plugins.  There's also a step which converts your code into a single JS file which is what gets passed to the Hermes compiler.

So it could be a few different things:
1. A bug in one of the babel transforms
2. A bug in one of the libraries you're using
3. A JS feature which Hermes does not yet implement
4. A bug in the Hermes implementation of some feature in JS

In order to distinguish, it would be very helpful to see what the actual input to Hermes is.

At this point we're getting to the edges of my knowledge of RN packaging, so what I say here may not be entirely correct.  Hopefully it's enough to work things out.

If you are using metro, I think you may be able to see the raw JS by fetching a URL like `http://localhost:8081/index.js.bundle?platform=android&dev=true&minify=false`.  This file will likely be very large.  If you replace your app's `index.js` with this output temporarily, and run your app again with Hermes, it should fail the same way, but the stack trace will refer to this file.  Then you can extract the relevant parts and add them to the issue.

**Comment by mhorowitz** [comment]
Oh, one other request: the red box has additional stuff below it.  The `render` at the very bottom is the top of the additional content, which I hope is a JS stack.  Can you scroll down a bit, and post that screen, too?  Thanks.

**Comment by mhorowitz** [comment]
My current working theory is that the various transforms are combining to create invalid JS from the code at https://github.com/react-native-community/react-native-svg/blob/develop/src/elements/Svg.tsx#L116.

The change to react-native-animated was only a few weeks ago, and npm caches things, so I speculate that when you updated to Hermes, you also caused npm to update reanimated.

It would be a good experiment to now switch back to JSC, and see if the problem continues to occur there.

**Comment by likern** [comment]
@mhorowitz I could reproduce bug in this repository https://github.com/likern/hermes-do-not-transform-bug. 
It looks like it's related to pass **array of styles** to **Svg**. 

As far as I remember I haven't had this error previously (because styled-component css-prop always translates to array of styles).

I tried to test using JSC, but not sure that it's working.
I made **enableHermes: false** and **./gradlew clean** and uninstalled / installed application after that, but still see
`Is Hermes enabled? true` which comes from 
```js
const isHermes = () => global.HermesInternal !== null;
console.log(`Is Hermes enabled? ${isHermes()}`);
```

Now I think it's still somehow related to Hermes. If you could look at repository with reproduction that would be great.
Error message is different, but I think all these errors have the same root.
![photo5470147988765650745](https://user-images.githubusercontent.com/842306/86320593-dfaf7180-bc3f-11ea-972b-6f8835047762.jpg)

**Comment by mhorowitz** [comment]
Thanks for the repro repo.  That was very helpful.

First, I think both of us were misled by this incorrect code:
```
const isHermes = () => global.HermesInternal !== null;
```
`global.HermesInternal` is either undefined or an Object, so this will always be true.  I know this code appears in the RN docs.  https://github.com/facebook/react-native-website/pull/1965/files fixes it, but it hasn't been deployed to the web site yet.

I was able (with some effort) to get the test app running with JSC, and changing the above JS to
```
const isHermes = () => !!global.HermesInternal;
```
I can reproduce this error with JSC:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/290225/86413333-c6291c80-bc75-11ea-8674-89262b5419c3.png">
<img width="676" alt="image" src="https://user-images.githubusercontent.com/290225/86413420-0d171200-bc76-11ea-8f80-7cef7d9928af.png">

Based on my earlier hypothesis, I removed `react-native-reanimated/plugin` from `babel.config.js` in your repro, ran `react-native start --reset-cache` to clear the metro cache, and rebuilt the app with Hermes.  Now I get no red box, and instead a small grey circle in the corner.

At this point, I am confident this is not a Hermes bug.

Since it appears to be a bug in reanimated, I think the best place to follow up is on https://github.com/software-mansion/react-native-reanimated/issues/939 which I created, or you could create your own issue.
