### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by Bardiamist** [facebook/hermes#34]
What about iOS? Why only for Android?

**Comment by burhanyilmaz** [comment]
App forced to use V8 js engine. Hermes is a custom js engine.

- https://twitter.com/gereksizcoder/status/1150149439274848256
- https://thenextweb.com/apple/2013/04/04/will-chrome-for-ios-be-able-to-use-googles-new-browser-rendering-engine-blink/
- https://salmanually.com/2019/07/13/all-you-need-to-know-about-new-hermes-javascript-engine-how-to-migrate/

**Comment by zhigang1992** [comment]
section 2.17 of Apple’s App Store Review Guidelines state that “apps that browse the web must use the iOS WebKit framework and WebKit Javascript.”

But we are not apps that browse the web right?

**Comment by alastaircoote** [comment]
The important section is this one:

> 3.3.2 — An Application may not itself install or launch other executable code by any means, including without limitation through the use of a plug-in architecture, calling other frameworks, other APIs or otherwise. No interpreted code may be downloaded or used in an Application **except for code that is interpreted and run by Apple’s Documented APIs and built-in interpreter(s)**.

Apple requires that if you want to download and intepret JavaScript at runtime, you use JavaScriptCore. The key part here is _runtime_ - Flutter does not let you dynamically execute code at runtime, only compile it as part of your released app. With Hermes you could (in theory?) download bytecode remotely and execute it at runtime, which is what Apple forbids.

**Comment by tailang** [comment]
> Apple forced to use V8 js engine. Hermes is a custom js engine.
> 
> * https://twitter.com/gereksizcoder/status/1150149439274848256
> * https://thenextweb.com/apple/2013/04/04/will-chrome-for-ios-be-able-to-use-googles-new-browser-rendering-engine-blink/
> * https://salmanually.com/2019/07/13/all-you-need-to-know-about-new-hermes-javascript-engine-how-to-migrate/

 Apple forced to use  [JavaScriptCore](https://trac.webkit.org/wiki/JavaScriptCore)，not V8

**Comment by vovkasm** [comment]
Currently quotation from @alastaircoote is incorrect. Current statement is:

> 3.3.2 Except as set forth in the next paragraph, an Application may not download or install
executable code. Interpreted code may only be used in an Application if all scripts, code and
interpreters are packaged in the Application and not downloaded. The only exceptions to the
foregoing are scripts and code downloaded and run by Apple's built-in WebKit framework or
JavascriptCore, provided that such scripts and code do not change the primary purpose of the
Application by providing features or functionality that are inconsistent with the intended and
advertised purpose of the Application as submitted to the App Store.

Source: https://developer.apple.com/programs/information/Apple_Developer_Program_Information_8_12_15.pdf

So currently Apple don't force apps to use JSC, it only requires all executed code to be packed in app bundle. And only if you need to download code (technically speaking execute code without any review from Apple), only in this case code can be only executed with system JSC.

**Comment by cayomey** [comment]
I found the quotation from @vovkasm is still a little outdated (dated by to 8/12/2015).

[The latest version](https://download.developer.apple.com/Documentation/ADP_Program_License_Agreement/Apple_Developer_Program_License_Agreement_20190603.pdf) from https://developer.apple.com/terms/ is:

> 3.3.2 Except as set forth in the next paragraph, an Application may not download or install
executable code. Interpreted code may be downloaded to an Application but only so long as
such code: (a) does not change the primary purpose of the Application by providing features or
functionality that are inconsistent with the intended and advertised purpose of the Application as
submitted to the App Store, (b) does not create a store or storefront for other code or
applications, and (c) does not bypass signing, sandbox, or other security features of the OS.
>
> An Application that is a programming environment intended for use in learning how to program
may download and run executable code so long as the following requirements are met: (i) no
more than 80 percent of the Application’s viewing area or screen may be taken over with
executable code, except as otherwise permitted in the Documentation, (ii) the Application must
present a reasonably conspicuous indicator to the user within the Application to indicate that the
user is in a programming environment, (iii) the Application must not create a store or storefront for
other code or applications, and (iv) the source code provided by the Application must be
completely viewable and editable by the user (e.g., no pre-compiled libraries or frameworks may
be included with the code downloaded).

which not even mention JavaScriptCore at all.

**Comment by vovkasm** [comment]
Oh, sorry! Of course @cayomey are right. Latest term is at auth only page as he mentioned. And probably it even allows to download "interpreted code" (still needs to be proved by real published apps, imho).

**Comment by BogdanArdelean** [comment]
I think that Facebook is already using Hermes on iOS for a while now. There is a hbcbundle instead of a jsbundle in the Facebook app bundle. 
See it for yourselves:
https://imgur.com/OQ2duk0

**Comment by tklajnscek** [comment]
Is there any news on this? If nothing else we'd like to use Hermes on iOS for it's ability to remote debug sync react native code.

**Comment by zhigang1992** [comment]
V8 is now on iOS 

https://github.com/Kudo/react-native-v8/issues/31

**Comment by uday5162** [comment]
@zhigang1992 does hermes works on ios now?

**Comment by uday5162** [comment]
any update if not?
Any guidelines to improve app launch time?

**Comment by Eyesonly88** [comment]
Can we disable the ability to execute code dynamically at runtime so we can use it on iOS? 
I get that over the air updates is a big feature in RN which is what this dynamic execution helps with I assume. However, not all RN apps need this feature so maybe if we can disable it then Apple would be okay?

**Comment by tohami** [comment]
@zhigang1992 does hermes works on ios now?

**Comment by appcoders** [comment]
@tohami  Looks like see [Pull Request 332](https://github.com/facebook/hermes/pull/332)

**Comment by denissb** [comment]
I guess this one should be closed now as hermes is supported in iOS officially since 0.64.0: https://github.com/facebook/react-native/releases/tag/v0.64.0
