### ISSUE TITLE
Android build spams "warning: the variable 'somevar' was not declared in function"

### ISSUE THREAD

**Issue by AndrewMorsillo** [facebook/hermes#342]
## Bug Description

Build output is overrun with 10k+ lines similar to 

```
index.android.bundle:13:134: warning: the variable "Promise" was not declared in function "isBoldTextEnabled"
minified source code here for hundreds of lines
```

- [ X] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.5.2-rc1
React Native version (if any): 0.63.2
Android version (if any): N/A
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): N/A

## Steps To Reproduce
1. set `enableHermes: true`
2. `./gradlew assembleRelease`

## The Expected Behavior
Hermes build process should not spam entire app source code to console.

**Comment by tmikov** [comment]
Hermes is an ahead-of-time compiler, so it expects to have definitions of all symbols. This is happening because code references some symbols as globals, and Hermes does not include them in its list of standard JavaScript global properties. In strict mode, use of unknown globals causes a warning to be emitted which you see here. In practice, an earlier polyfill defines these symbols, so everything works.

There are a couple of solutions:
- You can just disable all warnings, you can follow the instructions here https://github.com/facebook/hermes/issues/216#issuecomment-615429942
- You can just disable the "undefined variable" warning by using `-Wundefined-variable`.
- Lastly, you can actually tell Hermes about these global symbols by using `--include-globals=filename`

By the way, with Hermes there is no need to minify the input. With non-minified input, the warnings look much better.

**Comment by AndrewMorsillo** [comment]
@tmikov AFAIK I'm not minifying the input -- it seems react native does that by default?

**Comment by AndrewMorsillo** [comment]
Sorry to ping a closed issue @tmikov but I don't understand your comment about no need to minify input. When using react-native how to we prevent it from minifying? It appears to do this by default and I can't find a way to change the behavior.

**Comment by tmikov** [comment]
@AndrewMorsillo sorry, RN's build process if outside of my area of expertise. You might have better lack asking in the RN community.

**Comment by gustavopch** [comment]
@AndrewMorsillo Here's how you disable minification to have better warnings:
```
project.ext.react = [
    extraPackagerArgs: [ '--minify=false' ]
];
```
