### ISSUE TITLE
Invalid function call gets wrongly parsed as property access

### ISSUE THREAD

**Issue by asklar** [facebook/hermes#380]
## Bug Description
```js
const x = 'hello';
x.length();
```

## The Expected Behavior
`x.length is not a function`

## Actual behavior:
`5 is not a function`
It seems like the parsing is too greedy and evaluates x.length, and then tries to apply the function call operator ()

**Comment by asklar** [comment]
Similar thing happens when passing a non-existent function:
```js
const x = 'hello';
x.foo();
```
The parser tries to use x.foo first and it gets undefined, and then tries to call undefined which is not a function, so the error message is the not-so-useful `undefined is not a function` instead of `foo is not a function`

**Comment by tmikov** [comment]
Hi, this is by design. Hermes is an AOT compiler, so the source is not available at execution time, and thus it is not possible to generate error messages like "foo is not a function" - that would require preserving the string for every call invocation in the compiled bytecode. While it is theoretically possible and it would be marginally helpful, such information is not really needed - the error message already contains the precise source coordinates of the error (line 2 column 9). The developer can easily examine the source.

The parsing and execution semantics of the examples are themselves correct - the text of the error message is not specified by ECMA-262, precise text of errors can and do differ between engines.
