### ISSUE TITLE
Hermes 0.5.2-rc1 crashes on react native 0.63.3

### ISSUE THREAD

**Issue by vidsag** [facebook/hermes#386]
## Bug Description

The app crashes with the following exception when I try to run on debug

`java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes-executor-debug.so caused by: dlopen failed: cannot locate symbol "_ZN8facebook6hermes8debugger8Debugger17triggerAsyncPauseEv" referenced by "/data/app/com.unacademyapp.debug-SWJwQ3RzywuePWzMf2Q2qg==/lib/arm64/libhermes-inspector.so"... result: 0`

I have verified  libhermes-executor-debug.so and libhermes-inspector.so are present.

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.5.2-rc1
React Native version (if any): 0.63.3
Android version (if any): 10
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):  arm64-v8a

**Comment by YoranRoels** [comment]
Did you manage to fix this issue? 
We are experiencing the same issue after upgrading to R-N 63.3.

**Comment by vidsag** [comment]
The issue was due to a custom aar we were using for ReactAndroid. so we had include the dependencies of that which were
    implementation("com.facebook.infer.annotation:infer-annotation:0.11.2")
    implementation("javax.inject:javax.inject:1")
    implementation("androidx.appcompat:appcompat:1.2.0")
    implementation "androidx.localbroadcastmanager:localbroadcastmanager:1.0.0"
    implementation("com.facebook.fresco:fresco:2.0.0")
    implementation("com.facebook.fresco:imagepipeline-okhttp3:2.0.0")
    implementation("com.facebook.soloader:soloader:0.6.0")
    implementation("com.google.code.findbugs:jsr305:3.0.2")
    implementation("com.squareup.okhttp3:okhttp:3.12.1")
    implementation("com.squareup.okhttp3:okhttp-urlconnection:3.12.1")
    implementation("com.squareup.okio:okio:1.15.0")

I believe it was due to mismatch on one of these dependencies with RN 63.3.

**Comment by Marinaarimany** [comment]
Hello,
I have the same worries, I've been going around in circles for several weeks because of hermes, I'm depressed: /

SoLoader: couldn't find DSO to load: libhermes-inspector.so caused by: dlopen failed: cannot locate symbol "_ZTIN8facebook6hermes8debugger13EventObserverE" referenced by "/data/data/com.test/lib-main/libhermes-inspector.so". .. result: 0
2020-11-03 11: 09: 53.512 16167-16270 / com.test E / SoLoader: couldn't find DSO to load: libhermes-executor-debug.so caused by: couldn't find DSO to load: libhermes-inspector .so caused by: dlopen failed: cannot locate symbol "_ZTIN8facebook6hermes8debugger13EventObserverE" referenced by "/data/data/com.test/lib-main/libhermes-inspector.so" ... result: 0 result: 0
2020-11-03 11: 09: 53.558 16167-16272 / com.test A / libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffffff in tid 16272 (mqt_js), pid 16167 (com.test )

Can somebody help me please ?

**Comment by jonathanm-tkf** [comment]
same here

**Comment by manpreetsingh3215** [comment]
please help....   i am also stuck on this issue... keep on crashing on start
