### ISSUE TITLE
How does hermes optimize memory storage?

### ISSUE THREAD

**Issue by QuXing9** [facebook/hermes#401]
#### Problem

Hello! There is an interesting [report](https://github.com/facebook/hermes/issues/134). 

When initializing an array whose size up to 904862 in reverse order, Hermes spent nearly 31 minutes. It's too much time for Hermes. As you explained, this is caused by a memory optimization of Hermes. And I notice that reducing memory usage is a primary metric of Hermes. 

Well, I am confused about the following two questions, Could you help me? Thanks~

-  Why does Hermes take normal time when assigning value in positive order? Does not Hermes need to reallocate memory in positive order?
- How does Hermes optimize memory storage? Are there some documents or source codes for reference?  

Looking forward to your reply！Thanks again!

**Comment by tmikov** [comment]
For simplicity and to maintain small binary footprint, Hermes assumes that arrays will be used in the "natural" way and elements will be added from the beginning. For each array we allocate memory enough to store the range containing the first and last non-empty array element. 

So, if you do this:
```
a = []
a[10] = "aaa";
a[19] = "bbb";
```
we will allocate a chunk of memory enough for 10 elements. From index 10 to index 19 inclusive.
If you then do:
```
a[20] = "ccc";
```
we will allocate a new chunk with double the size of the previous one (so it will be large enough for 20 elements) and we will copy the data into it. Then, if you keep adding elements, we don't need to allocate anything for the next 9 elements. And so on. Since every chunk we allocate is twice the size of the last one, we will perform only `log2(N)` allocations and copies of the array if you keep adding elements in the natural way. This is a standard implementation of dynamic arrays.

By contrast, if you do:
```
a[9] = "@@@";
``` 
we either need to allocate a new chunk and copy the elements there, or we need to shift all elements in the existing chunk if there is space in the end. Either way, we end up copying all the existing elements. There is no way to avoid that copy without resorting to significant complexity.

**Comment by QuXing9** [comment]
Thanks for your quick reply, the description is detailed. 

Now there is an extended question:

After initializing the index from `10` to `19` of the array, Hermes will allocate a chunk of memory of length 10. If I then do:

```javascript
a[100] = "ccc";
```

instead of 

```javascript
a[20] = "ccc";
```

How many times does Hermes need to reallocate enough memory?

Four times?  According to the principle of double the size of the previous one.  The lengths of the four allocations are 20,40,80 and 160.

**Comment by tmikov** [comment]
It will reallocate exactly once. When reallocating, the new size has to be sufficient to at least hold all of the elements.

**Comment by QuXing9** [comment]
Got it!  Thx!
