### ISSUE TITLE
Bytecode to Javascript

### ISSUE THREAD

**Issue by Jm-Zion** [facebook/hermes#434]
Hi,

Is it possible to extract the javascript from the index.android.bundle for apps using Hermes JS Engine ? 
I know I can get the bytecode in readable human way with hermes-engine-cli commands but I didn't found something that could allow me to extract the javascript, neither in the documentation neither in the cli.

Thanks,

**Comment by mhorowitz** [comment]
You can't extract the JavaScript because it is not there to extract.  Compilation removes a lot of information about the original source, so this is not possible in general.  This is the same basic problem as going from machine language back to C++ source code.

A few simple examples of why this is not possible are inlining and constant folding.  If you write `foo(2+3)` in your source code, the bytecode (when optimizing) will add 2 and 3 at compile time, and so the bytecode will only include `5`.  There's no way to know if the source code said `5`, `2+3`, `50/10`, etc.  There are other possible transformations which could change the structure of the program even more significantly.  Also, compilation will remove most variable names.

In theory, one could probably build a tool which generates JavaScript code which would compile back into the same bytecode again, but the code would likely look very different from the original source.  Hermes does not include such a tool, nor am I aware of one, and we have no plans to build one.
