### ISSUE TITLE
Hermes version 0.7.2 marked as vulnerable CVE-2020-1914

### ISSUE THREAD

**Issue by lnadudva** [facebook/hermes#453]
Dear Hermes Team,

Black Duck scans Hermes version 0.7.2 as still vulnerable to CVE-2020-1914, whereas this should be fixed by [this commit.](https://github.com/facebook/hermes/commit/379760bbc5a27802917ac9e7847da356df9c9660)

Vulnerability Description: A logic vulnerability when handling the SaveGeneratorLong instruction in Facebook Hermes prior to commit b2021df620824627f5a8c96615edbd1eb7fdddfc allows attackers to potentially read out of bounds or theoretically execute arbitrary code via crafted JavaScript. Note that this is only exploitable if the application using Hermes permits evaluation of untrusted JavaScript. Hence, most React Native applications are not affected.

Is this issue something that the Hermes team should resolve, or is this a Black Duck issue?

Thank you very much for your help.

**Comment by tmikov** [comment]
Hermes 0.7.2 should contain the fix. Can you provide some more information how it was established that Hermes is vulnerable, etc? Without that there is not much we can do on our side.

**Comment by petergreen86** [comment]
https://nvd.nist.gov/vuln/search/results?adv_search=true&query=cpe%3A2.3%3Aa%3Afacebook%3Ahermes%3A0.7.2%3A*%3A*%3A*%3A*%3A*%3A*%3A*

**Comment by jpporto** [comment]
Hi,

Thank you for your message. We are currently unaware of any unfixed CVE's in hermes. We also don't have access to blackduck scans/reports. Can you please share more details about what your concern is, exactly? For example, which CVE are you concerned about?

John Paul

**Comment by yasodha-r** [comment]
Hi @jpporto , Sorry for the delayed response. Below are the one of the CVE details,
CVE-2022-35289
(BDSA-2022-3076)
Description
A write-what-where condition in hermes caused by an integer overflow, prior to commit 5b6255ae049fa4641791e47fad994e8e8c4da374 allows attackers to potentially execute arbitrary code via crafted JavaScript. Note that this is only exploitable if the application using Hermes permits evaluation of untrusted JavaScript. Hence, most React Native applications are not affected.

How to fix it
Solution - Fix Available
Fixed in [0.12.0](https://github.com/facebook/hermes/releases/tag/v0.12.0) by [this](https://github.com/facebook/hermes/commit/5b6255ae049fa4641791e47fad994e8e8c4da374) commit.

The latest stable releases can be found [here](https://github.com/facebook/hermes/releases).

**Comment by tmikov** [comment]
The CVEs are only relevant when using Hermes with untrusted code. Such use case that is **explicitly not supported** and **absolutely not recommended**.  Untrusted code should be sandboxed.

Further, some of the CVEs have been incorrectly assigned to compile time JavaScript-only modules (hermes-parser, hermes-estree).

Lastly, all known CVEs in Hermes have been fixed.

Closing, since there is nothing actionable.
