### ISSUE TITLE
0.5.3 is not published to npm

### ISSUE THREAD

**Issue by kelset** [facebook/hermes#459]
## Bug Description

According to the release tab, since Nov 2020 there should be a [0.5.3](https://github.com/facebook/hermes/releases/tag/v0.5.3) release of Hermes available.

Problem is, according to npm [it's not there](https://www.npmjs.com/package/hermes-engine).

## Steps To Reproduce

1. use yarn resolution to force hermes-engine to version 0.5.3
2. run yarn install
3. see yarn telling you 0.5.3 doesn't exist:
> Couldn't find any versions for "hermes-engine" that matches "0.5.3"

## The Expected Behavior

0.5.3 should be available via npm.

**Comment by Huxpro** [comment]
@kelset sorry for the confusion. The 0.5.3 was to support only the RN macOS arm64 (see https://github.com/facebook/hermes/pull/390) hence it's only published to the <https://www.npmjs.com/package/hermes-engine-darwin>

That being said, is there any use case other than RN macOS of 0.5.3 you are looking for?

My assumption is that RN used the `0.5.x` so the most recent patch releases would be used (`0.5.2` for `hermes-engine`).

**Comment by jcamins** [comment]
@Huxpro there doesn't seem to be a `0.5.2` release either, just a release candidate.

**Comment by Huxpro** [comment]
@jcamins Oops, yeah you are right there is no`0.5.2` and `0.5.2-rc1` was made for opting-in Proxy.

But my assumption still hold, RN 0.63 would pick whatever the most recent patch release is. There was no important addition after `0.5.1`. 

Does this break any tooling (that based on some assumption of the existence of them) or create any problems? Is this a well-established convention?

**Comment by jcamins** [comment]
@Huxpro I want to try using hermes in a project depending on Proxy. Since there is a non-prerelease version after the `0.5.2-rc1` release, I interpreted that to mean there is a stable version on the 0.5.x line with Proxy support. If 0.5.x with Proxy is not stable, I would expect there to be a `0.5.3-rc1` release instead.

**Comment by Huxpro** [comment]
@jcamins

> Since there is a non-prerelease version after the 0.5.2-rc1 release, I interpreted that to mean there is a stable version on the 0.5.x line with Proxy support.

There isn't. We marked it with `-rc` suffix so it can be opted in and it won't break non-Proxy user by accident in case the Proxy has bugs. 

But turns out it's already quite stable from the feedbacks at https://github.com/facebook/hermes/issues/33 so we enabled it by default at `0.7.0`.

That being said, I can see now why people may expect there is a stable `0.5.x` release with Proxy enabled. The reason it was not made was not technical but:
1. we assumed people wanting Proxy can find out `0.5.2-rc1` from https://github.com/facebook/hermes/issues/33 and test it out to see if that works for you 
2. the focus of our work were already moved to 0.7 and RN0.64

**Comment by Huxpro** [comment]
I've updated the release notes of https://github.com/facebook/hermes/releases/tag/v0.5.2-rc1 to reflect this out.

@jcamins thanks for this valuable feedback!

**Comment by jcamins** [comment]
Could I request one additional update to https://github.com/facebook/hermes/releases/tag/v0.5.3 along the lines of "Note: this release is only for Darwin-ARM64. Please use v0.5.2-rc1 for other platforms"? This way anyone seeing 0.5.3 on top will be alerted to use 0.5.2-rc1.

**Comment by Huxpro** [comment]
@jcamins Absolutely. Thanks for the input!

**Comment by Huxpro** [comment]
@kelset is your concern same as @jcamins? Feel free to close it if that's resolved.

**Comment by kelset** [comment]
👍
