### ISSUE TITLE
A performance problem about Array.prototype.unshift

### ISSUE THREAD

**Issue by YaoHouyou** [facebook/hermes#465]
#### Description 
When calling Array.prototype.unshift, the execution speed of hermes is much slower than other JavaScript engines.  Does hermes need to be optimized?

#### Version

[b6530ae](https://github.com/facebook/hermes/issues/463)

#### Testcase

```javascript
var foo = function(v) {
    for(var t = [], r = 0; r < 10000; r++) {
        t.unshift(1);
    }
}
var res = foo();
```

#### Execution time
hermes:  2177ms
[JerryScript](https://github.com/jerryscript-project/jerryscript): 29ms 
[XS](https://github.com/Moddable-OpenSource/moddable):  79ms

#### CPU

```
Intel(R) Core(TM) i9-9940X CPU @ 3.30GHzz
```

**Comment by dulinriley** [comment]
This performance pattern is very similar to one you'd get with the following modified code example:
```
var foo = function(v) {    
    for(var t = [], r = 10000 - 1; r >= 0; r--) {    
        t[r] = 1;    
    }    
}    
var res = foo();
```

Both of these examples populate an array in descending indices. However, Hermes runs this example about
3x faster than your example (500 ms vs 1.5 seconds on my computer).

I believe the difference in performance happens because Hermes's implementation of `Array.prototype.unshift`
is meant to work on arbitrary objects that are passed in, as the spec requires. We don't have a special fast path
for arrays to do the same thing as `t[r] = x`, which is a call to `ArrayImpl::resizeLeft`.

Note that this pattern is quite rare, and can be replaced by the slightly more optimized example I gave above
without changing its characteristics. In general, it's almost always better to fill an array from 0 to N instead of
N to 0. This applies to any `t[r]` operation, as well as calling `.push(...)` instead of `.unshift(...)`.

If you have an app/project that is negatively impacted by this we can re-examine, but it's probably easier to
rewrite the JS instead.

**Comment by YaoHouyou** [comment]
@dulinriley  Thank you for your reply.
