### ISSUE TITLE
Strings are not obfuscated

### ISSUE THREAD

**Issue by mateosilguero** [facebook/hermes#496]
## Problem

Strings are not obfuscated (keeps as plain text), like js code, so secrets and sensitive data could be exposed. Is this a normal behavior ? Is there a way to obfuscate/encrypt this code ?

## Additional Context

It happens in my project, but it could be reproduced on the playground.

<img width="1071" alt="Captura de Pantalla 2021-04-14 a la(s) 09 38 57" src="https://user-images.githubusercontent.com/25598400/114711548-75b31500-9d05-11eb-9ad6-7032e4fc4b68.png">

(graphql query as plain text on index.android.bundle)

<img width="551" alt="Captura de Pantalla 2021-04-14 a la(s) 09 43 51" src="https://user-images.githubusercontent.com/25598400/114711983-f5d97a80-9d05-11eb-9ad2-f79f048a2c16.png">

**Comment by dulinriley** [comment]
Can you give us some more context on why you want to encrypt/obfuscate stuff? Is the goal to prevent someone from reverse-engineering the source code? Or is this to protect something like a key?

Hermes stores string literals in a table near the beginning of a bytecode file. This allows us to use string literals without allocating them on the heap immediately, reducing GC pressure. This optimization wouldn't work if the strings were encrypted, because encrypted strings would have a different length (to prevent length-based analysis). So we can't do this automatically for every string without a significant performance hit.

You could encrypt this manually and decrypt it in memory only when needed using the encryption algorithm of your choice. A safer alternative would be to never let the secret reach a client device at all. Since a client could typically dump the contents of their own memory and scan through it for any important strings.

**Comment by dulinriley** [comment]
You might want to look into obfuscation as part of your source code generation pipeline.
For example, this tool https://obfuscator.io/ would obfuscate your source code that is generated before it's sent to Hermes. That way it'll also work on other VMs like v8 or JSC (which run on source code anyway)

**Comment by mateosilguero** [comment]
Thanks for the explanation @dulinriley ! 

Yes, main idea was hide keys or secrets from code, now im trying obfuscator+hermes and its seems working for my use case.
