### ISSUE TITLE
Hermes does not build for React Native macOS on ARM64

### ISSUE THREAD

**Issue by Saadnajmi** [facebook/hermes#514]
## Bug Description

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.5.1
React Native version (if any):
OS version (if any): macOS 11.3.1
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): macOS on arm64 (AKA, an M1 Mac mini

## Steps To Reproduce

1. Clone the react-native-macos repo (https://github.com/microsoft/react-native-macos)
2. Setup RNTester & open Xcode project (`yarn && cd RNTester && pod install && open RNTesterPods.xcworkspace`)
3. Try to build RNTester-macOS for Target "My Mac" (in my case it's am M1 Mac mini)

## The Expected Behavior

It builds successfully

## Actual Behavior

Several Errors:

![Screen Shot 2021-05-06 at 2 37 13 PM](https://user-images.githubusercontent.com/6722175/119443701-a5374300-bcef-11eb-9fd0-b1ce570ab202.png)

**Comment by Saadnajmi** [comment]
Cross reference https://github.com/microsoft/react-native-macos/issues/781

**Comment by Saadnajmi** [comment]
Looks like this will be fixed by https://github.com/facebook/hermes/pull/475 =)

**Comment by Huxpro** [comment]
@Saadnajmi Hey yes it's a KP and you've found the PR correctly. We are going to merge it soon but you'll need to upgrade to RN 0.65 and Hermes 0.8 to be able to use it ;)

**Comment by Saadnajmi** [comment]
@Huxpro Oh hey, I recognize you from the Callstack podcast! Noted, why do we need to be on RN 0.65?  Would it not work with 0.63 or 0.64?

**Comment by Huxpro** [comment]
@Saadnajmi 😛

> why do we need to be on RN 0.65? Would it not work with 0.63 or 0.64?

We may try to cherry-pick this fix to Hermes 0.7 and make a patch release (e.g. 0.7.3) for RN 0.64 (likely to work). I'm not sure how to make https://github.com/facebook/hermes/pull/475 working on Hermes 0.5 since the code changed was not even there back to 0.5. 🤔  cc @alloy.

I thought RN macOS 0.64 had released (from the <https://microsoft.github.io/react-native-windows/>) but from <https://github.com/microsoft/react-native-macos/releases> it seems not?

**Comment by Saadnajmi** [comment]
@Huxpro Yep! We're not caught up yet on RN-macOS😅. 
I was mostly curious what the difference was between versions. Good to know there's a dependency. Thanks for the info!
