### ISSUE TITLE
new Date constructor with date string "Sun Aug 22 2021" not working 

### ISSUE THREAD

**Issue by sbin1211** [facebook/hermes#578]
Hermes version:
React Native version:0.65
OS version: android 11

new Date("Sun Aug 22 2021")

result:
return invalid Date

## The Expected Behavior
return valid date

**Comment by neildhar** [comment]
Hi @sbin1211, thanks for reporting this. The best way to get consistent behaviour across JS engines with regards to parsing dates would probably be to use ISO 8601 (e.g. "2021-08-22"), since that is laid out in [the spec](https://262.ecma-international.org/12.0/#sec-date-time-string-format). Other formats are implementation dependent.

That said, this seems to be supported by most other engines, so we should probably match their behaviour.

**Comment by neildhar** [comment]
Fixed in 14042455a43b131e94e86376e23e088e7136ba3f
