### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by Romick2005** [facebook/hermes#590]
## App crash

After app do some api request that require some loading indicator and navigation change app collapse with an error:
![image](https://user-images.githubusercontent.com/17779660/132332791-d9d0ef6e-9118-421d-8dab-78a6003fea88.png)

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.8.1
React Native version (if any): 0.65.1
OS version (if any): Android
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64 (M1 Apple Silicon)

## Steps To Reproduce
Any refresh layout operation.

App work fine when downgrade to react-native@0.64.2 (then it uses hermes-engine@0.7.2).
Also we have react-native-reanimated@2.3.0-alpha.2, tried different version, but result is the same. App crashes instantly on some simple actions, like pressing buttons -> save data-> 2sec -> crash.

## The Expected Behavior
No crash on Garbage Collector run.

**Comment by neildhar** [comment]
Hi @Romick2005, Hermes 0.8 includes a new concurrent garbage collector, which may run object finalisers in a background thread not registered with the JVM. The issue here seems to be that there is some object whose destructor attempts to interact with the JVM.

Since you're using 0.8.1, the bug that triggered this in `Intl` should be resolved. I noticed that the stack trace points to `libreanimated.so` perhaps there is a `HostObject` in reanimated that holds a JNI reference?

**Comment by piaskowyk** [comment]
Fixed in Reanimated - https://github.com/software-mansion/react-native-reanimated/pull/2389
