### ISSUE TITLE
expected a constructor, js engine: hermes

### ISSUE THREAD

**Issue by xks19943** [facebook/hermes#64]
can not use decorators ?  

import {connect} from 'react-redux';
@connect(
  state=>state.user
)
class Shop extends Component {
	render() {
		return (
			<SafeAreaView style={STYLE.ROOT}>
				<View style={STYLE.BACKGROUND}>
					<HeaderView
						headerTitle={'商城'}/>
					<Text>Shop</Text>
					<TouchableOpacity
            onPress={()=>{
            	this.props.navigation && this.props.navigation.navigate('AuthStack')
            }}>
            <Text>退出登录呀</Text>
					</TouchableOpacity>
				</View>
			</SafeAreaView>
		)
	}
}

but

 // export default connect(
//   state => {
//     console.log(state,'---')
//   }
// )(Shop);

is no problem

**Comment by avp** [comment]
It would be helpful to have more information so that we can debug this with you.

To help reproduce this, can you please upload a minimal JS bundle which demonstrates the error when run with Hermes? For example, a file `bundle.js` which when run with Hermes using `./hermes bundle.js` throws the error.

Alternately, you can put a small React Native project on GitHub which shows the issue when running Hermes on your Android phone and we can try and reproduce from there.

**Comment by Huxpro** [comment]
Stale enough, closed.
