### ISSUE TITLE
Hermes 0.10 has invalid Bitcode

### ISSUE THREAD

**Issue by mrousavy** [facebook/hermes#649]
## Bug Description

I've tried to upgrade to React Native 0.67-4 (which uses Hermes 0.10) and published a version to TestFlight.
While the build & publish succeeded, I got the following response from apple:

-----

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "XXXXXXXXX" 1.0 (9). Please correct the following issues, then upload again.
> 
> **ITMS-90562**: Invalid Bundle - The app cannot be processed because options not allowed to be embedded in bitcode are detected in the submission. It is likely that you are not building the app with the toolchain provided in Xcode. Rebuild your entire app with the latest GM Xcode and submit the app again.
> 
> Best regards,
> 
> The App Store Team

-----

Note that the app builds and runs fine (in debug at least), it's just that AppStore Connect rejects the app.

Hermes version: 0.10.
React Native version (if any): 0.67-4
OS version (if any): iOS 15
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): All / Bitcode ipa

## Steps To Reproduce

1. Install React Native 0.67 (with Hermes)
2. Build and publish app to TestFlight/AppStore

## Related

Maybe these two commits are somewhat related?

1. https://github.com/facebook/hermes/commit/af681862378732c914fbc0f9c2d26720f0f88c64
2. https://github.com/facebook/hermes/commit/fc8e622bb682129da2ee8999f83ac28b38842dff

Also, maybe this guide can help: [Resolving “ITMS-90562: Invalid Bundle” email from App Store](https://medium.com/360learning-engineering/resolving-itms-90562-invalid-bundle-email-from-the-app-store-d4a1030418e5) - I'd guess that there is some Framework not correctly listed for Hermes?

**Comment by kelset** [comment]
cc @neildhar @tmikov (who worked on those commits)

**Comment by mrousavy** [comment]
@neildhar @tmikov DM me on discord if you want to see the `.xcarchive`. Uploaded both the working one (RN 0.66) and the one that got rejected (RN 0.67) to Google Drive.

**Comment by mikehardy** [comment]
I cross-linked this to the 0.67 release post, someone else stubbed their toe on it unaware it was a known issue. Just trying to save folks time before they try it https://github.com/reactwg/react-native-releases/discussions/1#discussioncomment-1748583

**Comment by grabbou** [comment]
Interestingly, you can rebuild from Bitcode locally to try to get a better error description: https://github.com/googlesamples/mlkit/issues/347#issuecomment-911993580.

Dropping as a reference in case someone wants to give it a go.

**Comment by mrousavy** [comment]
Mike I tried that twice and Xcode/Organizer kept crashing 😄

**Comment by grabbou** [comment]
> Maybe these two commits are somewhat related?

Not sure about that one, but I might be of course wrong. In my opinion these commits are not the ones that are breaking 0.10 release.

The commits that you have referred are about unlinking CoreFoundation in the targets where it is not used. 

Assuming that the error is because some frameworks are missing (which is what the guide you've linked suggests as as solution for this error message), this can't be true for CoreFoundation which is always present on a device.

If you look at the output from otool:
> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1854.0.0)
> @rpath/libswiftDispatch.dylib (compatibility version 1.0.0, current version 9.0.0, weak)

CoreFoundation is referred from `System`, whereas other frameworks are referred from `@rpath`, which is a Frameworks directory.

That said, we have about 653 files changed between 0.9 and 0.10 to inspect -> https://github.com/facebook/hermes/compare/v0.9.0...v0.10.0

**Comment by billnbell** [comment]
what is the status of 0.10 ?

**Comment by cristianoccazinsp** [comment]
Is this fixed with 0.11 ? Looking forward to upgrade from 0.9, but curious about this.

**Comment by neildhar** [comment]
@cristianoccazinsp Yes, this is fixed in 0.11

**Comment by johnf** [comment]
I'm seeing the same app store issue with hermes on 0.68-rc.2, which has 0.11

**Comment by kelset** [comment]
@johnf could you expand a bit on what you are experiencing? Are you getting the same rejection? Is your setup custom in some way (RN can be used in a lot of different ways so the more info you can share, the better)?

**Comment by johnf** [comment]
I'm seeing the same ITSM-90562 error.

I'll revert tomorrow, I need to confirm 100% that this is the reason why. I've made a number of major changes since I last pushed to the store including
* Updating to 0.68-rc.2
* Adding react-native-renamiated2 so I can use draw navigation in react-navigation
* Which meant I needed to enable hermes
I'll try and do some git bisecting tomorrow to workout where it broke

**Comment by kelset** [comment]
cool - keep up posted 🙏

@mrousavy could you double-check if with your app things go smoothly with RC2+Hermes?

**Comment by johnf** [comment]
So I made sure my GitHub runner had no pod cache or compile cache and performed a brand new build and am seeing the same issue.

I get two errors from apple

> ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path. 
> ITMS-90562: Invalid Bundle - There's an issue with the app's bitcode compilation. Rebuild the app using the current public (GM) version of Xcode and upload it again. 

I'll try some bisecting to make sure it isn't something else I've done.

**Comment by johnf** [comment]
This ended up being my fault. I was missing a setup in my Podfile for react-native mapbox

**Comment by manosKas** [comment]
so im on rn 0.67.3 and hermes-engine 0.9.0 and i want to update hermes 
should i just update rn to 0.68 ?
