### ISSUE TITLE
Profiling JS and creating Flame Graphs on Hermes (with Flipper?)

### ISSUE THREAD

**Issue by mrousavy** [facebook/hermes#663]
## Bug Description

Hi! 

An app I'm working on uses a lot of cryptography functions, which are, as expected, very slow when written in JS.

Sometimes a screen takes 7 seconds to load, so I'm now trying to profile the app to find out where exactly the bottleneck is. The codebase is huge, so I cannot really go down the code hierarchy to find "the one function that is slow", I need a way of visualizing the slowness. 
Ideally I want to create a Flame Chart / Flame Graph of that specific interaction, to then find out which functions are the bottleneck, aka which functions take the longest to execute. 
I then want to optimize those functions or move them to C++.

I tried to use Flipper with the Hermes Debugger (RN) plugin to open the Performance tab, but when pressing the "record" button I am stuck at this screen:

![](https://cdn.discordapp.com/attachments/624539540119486474/931153608660119603/Screenshot_2022-01-13_at_12.51.38.png)

And it never loads.

I would like to know if some of you guys have an idea on how I could create a flame graph manually, is there maybe a CLI tool to create this? And if there is, do Flame Graphs even show the function names on Hermes? I remember Hermes stripping those away, which would make this debug session useless.

Any help appreciated here!

Hermes version: 0.9
React Native version (if any): 0.67

**Comment by NathHorrigan** [comment]
Did you get anywhere with this @mrousavy ?

**Comment by mattbfb** [comment]
@mrousavy I'd recommend trying a newer version of Flipper. The version pictured in the original post has a different profiling interface. The current supported interface for profiling is the "Profiler" tab, rather than the "Performance" tab:

<img width="502" alt="Screen Shot 2022-09-14 at 10 25 40 AM" src="https://user-images.githubusercontent.com/111091151/190181911-c48ced6f-4300-45cc-96f0-85dcc4855e09.png">

If you can successfully collect a trace with the "Profiler" tab, you can use the drop-down menu at the top to switch between different renderings of the data:

<img width="497" alt="Screen Shot 2022-09-14 at 10 24 36 AM" src="https://user-images.githubusercontent.com/111091151/190181716-3f5b27c1-d6f5-4ceb-bd31-a19bd7ea49b9.png">

If you cannot collect a trace using the "Profiler" tab, updating to the current version of React Native may be helpful.
