### ISSUE TITLE
Variables created dynamically using eval function have reference problem.

### ISSUE THREAD

**Issue by dy2-X** [facebook/hermes#674]
## Bug Description

Variables created/accessed dynamically using eval function have reference problem when Hermes enabled. The issue is observed in both iOS and Android.

React: 17.0.2
RN: 0.67.1
Hermes: 0.10.0

code example:

render() {
const { leds } = this.props
const { CM, CL, BT, BM, BA, BS, BR } = leds

const actionNameList = ["BM", "BA"]

return (
actionNameList.map( el => (
<CtrlBtn
... 
ledValue={eval(el).value} 
actionName={el}
...
>
</CtrlBtn>
))
);
}

**Comment by dy2-X** [comment]
It is working expectedly when Hermes disabled.

**Comment by tmikov** [comment]
Hermes explicitly does not support "local eval" (eval that refers to values of non-global variables): https://github.com/facebook/hermes/blob/main/doc/Features.md#excluded-from-support

Further, we strongly recommend against using eval() at all, unless absolutely necessary, since it is very slow and can defeat most compiler optimizations, even in engines that do support "local eval".

**Comment by dy2-X** [comment]
Thanks for your answer, @tmikov. 🤙🏻

I apologize for missing out information at the link.

We used it in parts where we needed flexibility of the code rather than performance.  We're going to have to refactor most of them. 😟
