### ISSUE TITLE
Support for structuredClone

### ISSUE THREAD

**Issue by Andarius** [facebook/hermes#684]
## Problem

To deep clone an object today, one can either use `JSON.stringify` or `lodash.cloneDeep`. There is no dedicated way of creating a deep copy in an efficient manner.

## Solution

A solution could be implementing: `structuredClone` (see https://developer.mozilla.org/en-US/docs/Web/API/structuredClone)

**Comment by ljharb** [comment]
structuredClone isn’t part of the language; but it may be in the medium term. Currently, it’s a web api, so I’m not sure it makes sense for Hermes to have it.

**Comment by tmikov** [comment]
I think one way to look at this is, is it provided by the engine or the browser? For example, is it available in Node?

**Comment by ljharb** [comment]
node does not provide it currently. If they did, it'd be like setTimeout, where they're mirroring the browser without a spec compelling them to do so.

**Comment by migueldaipre** [comment]
Hey guys, In node v17 it is already present, doesn't it make sense to have it in Hermes too? 
 https://nodejs.org/en/blog/release/v17.0.0/

**Comment by joe-sam** [comment]
structuredClone is now supported in the facebook/jest and facebook/lexical repository.  
Right now the only way is 3d party libs which often don't work correctly or the spread operator which only does a shallow copy.

**Comment by cjshearer** [comment]
I'd love to see this in react-native. `structuredClone` is [available in the majority of other environments](https://caniuse.com/?search=structuredClone) and provides significant performance advantages over js implementations that don't have direct memory access.

**Comment by tmikov** [comment]
Note that in each case `structuredClone()` doesn't seem to be provided by the engine itself, instead it is provided by the integration (the browser, etc). At least my experiments with all the engines available for mac64arm from jsvu, show that it isn't available in any.

People commonly confuse the browser with the engine itself. This has been a common topic in several issues submitted here, where users are requesting APIs that are not part of the EcmaScript spec. I have suggested that it might make sense to create community "integration" repository for such extensions, but there has been no interest.

With all that said, admittedly, an implementation of `structuredClone()` based on JSI would likely be significantly slower than one using internal Hermes APIs. So, theoretically there would be some value in a built-in implementation. The problem is that builtin APIs change all the time and increasing the usage area increases the maintenance cost.

**Comment by tmikov** [comment]
FYI https://github.com/facebook/hermes/discussions/1072

**Comment by psnet** [comment]
its annoying to not have such commonly used API as `structuredClone` even if is not part of ES

`react` wants immutable state so for deep objects clone we should use 3rd party libs 😞

**Comment by tmikov** [comment]
We are actually working right now on implementing something may be used for structuredClone.

**Comment by psnet** [comment]
> We are actually working right now on implementing something may be used for structuredClone.

it will be great! of course we dont need full copy of `structuredClone` (like Buffers, etc) but common case is to deep copy arrays and objects (maybe w/o cyclic links) - it will help in most projects
