### ISSUE TITLE
Default behaviour for static built-ins

### ISSUE THREAD

**Issue by mayantmukul** [facebook/hermes#741]
Hi, we got a significant decrease in startup time and overall performance considerably improved just by using `-fstatic-builtins`. I was wondering why this is not on by default? Are there any caveats to keep in mind?

We're using React Native v0.63.4 and Hermes v0.5.1

Thanks!

**Comment by tmikov** [comment]
@mayantmukul "-fstatic-builtins" makes the compiler assume that functions listed in https://github.com/facebook/hermes/blob/main/include/hermes/FrontEndDefs/Builtins.def have not been overridden or polyfilled, allowing the compiler to use a faster calling convention to invoke them.

It would be risky to enable it by default for all applications, since that would violate the JS spec in a pretty dramatic way, but the intent is that one should enable it on case by case basis, just like you have apparently done.

**Comment by mayantmukul** [comment]
Got it, thanks!
