### ISSUE TITLE
Maybe Memory leaks caused by circular references

### ISSUE THREAD

**Issue by breakerrorchen** [facebook/hermes#742]
## Problem

If I export an Image object in c++ to JavaScript to use, like the following

`var image = new Image()`

At this point, the image holds a C++ object, and the C++ object will not be released if the JS object is not GC.
But if give the Image a callback, that callback holds the Image itself，like the following

`var image = new Image();
 image.on_load = function() {
  if (image.status) {
     .........
  }
}`

In theory C++ will hold callbacks at this point, but the callback holds the image of the image, and the image object holds the C++ object, so the reference is cyclic.

Is there any good way to solve this memory problem automatically?

**Comment by breakerrorchen** [comment]
Is it possible to provide a callback function that allows the program to marker some weakObject that does not release before the kernel performs GC behavior?

**Comment by jpporto** [comment]
Hi,

Thank you for your question. Let me summarize what you wrote to make sure I understand your scenario: you have a JS object, ```image```, which has an ```on_load``` member initialized to a ```function() {...}``` which itself references image ```image```. As you pointed out, that scenario introduces a dependency cycle, but that should not be a problem in Hermes as it does not use [reference counters](https://en.wikipedia.org/wiki/Reference_counting).

Hermes has a precise garbage collector: it tracks "roots" (e.g., variables in your program) and it will collect any objects that are not reachable from a root. In your example, ```image``` is the only root. Thus, once you make it reference anything else, the ```new Image()``` object will become unreachable (image.on_load is not a root because it can't be reached unless you can reach image), and eventually be collected by the garbage collector.

There is no standard way to "force" a garbage collection to occur, and JS code should not depend on it running. For example, in Hermes, GC will only happen once the program tries to allocate heap space and the allocation fails due heap exhaustion. Depending on the garbage collector you're using, this collection may not even be a "full GC" (for example, Hermes' Hades GC is a [generational collector](https://en.wikipedia.org/wiki/Tracing_garbage_collection#Generational_GC_(ephemeral_GC)))

Let me know if you have other concerns,
John Paul

**Comment by breakerrorchen** [comment]
Thanks for your reply.
Maybe I didn't describe the problem clearly.

First of all, Image is provided by C++ to the JS engine, and on_load is also a C++ provided function. When I call this function passing a JS callback function as an argument, the C++ function internally holds the callback function as a member object of the Image C++ object.

At this point, since C++ holds the callback function, the callback function internally holds the JS Image object. Also C++'s Image object is bound to JS's Image object. So, at this time, the GC has no way to find out that this object needs to be released.

**Comment by breakerrorchen** [comment]
> Thanks for your reply. Maybe I didn't describe the problem clearly.
> 
> First of all, Image is provided by C++ to the JS engine, and on_load is also a C++ provided function. When I call this function passing a JS callback function as an argument, the C++ function internally holds the callback function as a member object of the Image C++ object.
> 
> At this point, since C++ holds the callback function, the callback function internally holds the JS Image object. Also C++'s Image object is bound to JS's Image object. So, at this time, the GC has no way to find out that this object needs to be released.

@jpporto

**Comment by jpporto** [comment]
No worries! :)

I am having a hard time reconciling 

```javascript
var image = new Image(); image.on_load = function() { if (image.status) { ......... } }
```

with

>First of all, Image is provided by C++ to the JS engine, and on_load is also a C++ provided function. When I call this function passing a JS callback function as an argument, the C++ function internally holds the callback function as a member object of the Image C++ object.

I don't see any C++ in the example (which will not leak once you do ```image = null```), and the VM doesn't automatically know about any references to JS objects that exist outside of the JS. Can you provide a full example, including the C++/JS interaction? That would be the best way for me to understand your scenario.

**Comment by breakerrorchen** [comment]
v8 provides a function like this
`V8::AddImplicitReferences`, which is used to notify the JS engine before GC.  If the C++ objects represented by two JS objects have references at the C++ level.

In this case, the JS engine's marker sweep algorithm is not aware of it

@jpporto

**Comment by jpporto** [comment]
Thanks, that helps. :)

You are using jsi, and all jsi::Objects are GC roots. As you pointed out, will effectively prevent GC from reclaiming ```image```.

You could use a ```jsi::WeakObject``` instead of a ```jsi::Value```, e.g.,

```c++
class CXX_Image : public HostObject {
    virtual Value get(Runtime& runtime, const PropNameID& name) {
        auto name = name.utf(runtime);
        if (name == "on_load") {
            return Function::createFromHostFunction(runtime, name, 1,
                [](Runtime& rt, const Value& thisVal, const Value* args, size_t count) {
                    assert(count >= 1);
                    Object object = thisVal.getObject(rt);
                    auto _image = object.getHostObject<CXX_Image>(rt);
                    if (args[0].isObject()) {
                        _image->on_load_obj_ = std::move(args[0]).getObject(rt);
                    } else {
                        _image->on_load_value_ = args[0];
                    }
                });
    }

    Value on_load(Runtime &rt) {
        Value ret = obj_load_value_;
        if (on_load_obj_) {
            if (auto o = on_load_obj_.lock(rt)) {
                ret = std::move(o);
            } else {
                // on_load_obj_ has been released; it is likely that this has been deleted
            }
            return ret;
        }

public:
    Value obj_load_value_;
    WeakObject on_load_obj_;
};
```

which (I think) will allow Hermes' GC to recognize that on_load_obj_ (i.e., your JS callback) is eligible for GC as long as it is not reachable though other roots. Note that the callback reference to ```image``` (the ``` if (image.status)``` in your JS example) is not considered a root, and thus should not prevent GC from reclaiming the object. "I think", as I have limited experience with jsi.

Give that a try and let us know if that doesn't fix your issue.
John Paul

**Comment by breakerrorchen** [comment]
Thanks for your reply.

> ```c++
> _image->on_load_obj_ = std::move(args[0]).getObject(rt);
> ```

I think this callback should not be released as long as the C++ CXX_Image is not released in the real environment, which may require subsequent calls to this callback function.

But when I look at the code above, it just holds a weak reference. This may not match the logic

To change the example, let's say this is a DOM element and add a callback for a click on the DOM element. As long as the callback is added and this DOM element still exists, subsequent events should be able to notify the callback function

chenguodong

**Comment by breakerrorchen** [comment]
So I think the JS engine should provide a mechanism to solve this kind of problem

@jpporto

**Comment by breakerrorchen** [comment]
I'm emulating the browser DOM in this way, and it's really hard to do without support for this feature

**Comment by tmikov** [comment]
@breakerrorchen we are aware of this limitation. Internally, the Hermes engine does support this, but it is difficult to come up with a way to express it portably in a cross-engine API like JSI.

The root problem is that JSI doesn't have information about which JSI value belongs to which object, so it must treat all references as GC roots.

**Comment by breakerrorchen** [comment]
So I'm using Hermes' API directly instead of JSI's. Is there a workaround?

So can you tell me approximately which way?

@tmikov

**Comment by breakerrorchen** [comment]
I see that both JSC and V8 have additional interfaces for C++ to tell the JS engine about the existence of additional reference relations before GC.

@tmikov

**Comment by neildhar** [comment]
@breakerrorchen If you're using Hermes' API directly without JSI, then you could take a look at [DecoratedObject](https://github.com/facebook/hermes/blob/main/include/hermes/VM/DecoratedObject.h). `DecoratedObject` allows you to manage some native state associated with an otherwise regular JS object. It does not intercept property accesses (although you could get that by adding a `Proxy`), and you can store JS properties on it, which will then be collected normally.

If you do want to use JSI, you could simulate something similar by having a regular JS object that has a `HostObject` as a property. You can then store/retrieve the native state on the `HostObject`, but keep all JS references as properties on the JS object.

**Comment by neildhar** [comment]
Hermes now also provides a `NativeState` API which you can use to associate arbitrary native data with an object. Unlike a `HostObject`, you can also add regular JS properties to an object with `NativeState`, which in many cases allows you to avoid creating cycles with JSI references.
