### ISSUE TITLE
CLI tools with newer versions of Hermes

### ISSUE THREAD

**Issue by zolbooo** [facebook/hermes#767]
## Problem
Is there a way to use CLI tools as Hermes is now bundled with React Native? 

## Solution
It would be useful to deploy `hermes-cli` package or provide/document other way for npm packages and tools to invoke `hermes`/`hermesc` commands.

## Additional Context
As `hermes-engine` package is not updated with new RN versions, some packages/tools relying on it are broken, for example: https://github.com/microsoft/appcenter-cli/issues/1987

UPD: I found `hermesc` binary in `node_modules/react-native/sdks/hermesc`, is it a correct path to use?

**Comment by neildhar** [comment]
@zolbooo React Native now ships a copy of `hermesc`, which you should use. That compiler will be matched to the version of Hermes being used in RN apps.

It looks like the compiler you've found is the one that RN is using internally, so that would be the right one to use. ([source](https://github.com/facebook/react-native/blob/d9b8e07b0065db8371e849dcc5137aeb36a97e5a/react.gradle#L118))
