### ISSUE TITLE
Chrome debugging doesn't work. Can't open any source files.

### ISSUE THREAD

**Issue by trcoffman** [facebook/hermes#842]
## Bug Description

When using Chrome DevTools to debug a Hermes RN app, you can't open any of the source files to be able to place breakpoints.

Here's a screenshot. that index.bundle thing is the only thing you'll see. try typing in index.js, or other source files, nothing will appear.

![Screen Shot 2022-10-20 at 3 02 33 PM](https://user-images.githubusercontent.com/6195185/197071573-42a8b785-766d-4234-b448-fade184a27c6.png)

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: whatever is bundled with RN 0.70.1
React Native version (if any): 0.70.1
OS version (if any): iOS
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64-v8a

## Steps To Reproduce

1. Run your app.
2. Set up chrome devtools to connect to Metro Bundler.
3. Navigate to chrome://inspect .
4. Fire up the Hermes debugger.
5. Go to Sources.
6. Hit the hotkey to open a file (command-P on a mac).
7. Try typing in a source file like index.js
8. Nothing will show up other than this index.bundle URL.

code example:

https://github.com/react-native-community/rn-diff-purge

I'm using v0.70.1 of the RnDiffApp from rn-diff-purge to reproduce.

## The Expected Behavior

The expected behavior is that you should be able to open files and set breakpoints. It should behave the exact same as when you use Flipper. This works just fine in Flipper.

**Comment by mattbfb** [comment]
There have been some updates in standalone Chrome that prevent some source maps from loading in this scenario. We are looking into supporting these changes, but in the meantime, Flipper can provide a stable Dev Tools environment.

**Comment by trcoffman** [comment]
https://reactnative.dev/docs/hermes

In these docs, it would be good if chrome debugging was mentioned as being broken for the time being, and there should be some mention of flipper here with some links so that users can go download flipper.

**Comment by dillen-hub** [comment]
Hi

**Comment by ClementeSerrano** [comment]
having the same issue. I followed step by step what it is specified on [React Native docs for Hermes debugging on Chrome](https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools), and can't make *Sources* code to load. Weirdly, the *Console* debugging works.

**Comment by skurgansky-sugarcrm** [comment]
> having the same issue. I followed step by step what it is specified on [React Native docs for Hermes debugging on Chrome](https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools), and can't make _Sources_ code to load. Weirdly, the _Console_ debugging works.

just set Hermes to false and enjoy easy life :)

**Comment by Saeid-Barzegar** [comment]
i found a solution that made my day!
sharing maybe can help someone like me to don't spend one working day to resolve it :))

NO! need to remove the problem! 
just let's resolve it!

in chrome or like my case in Brave browser open this address
Brave: brave://inspect/#devices
Chrome: chrome://inspect/#devices

<img width="567" alt="image" src="https://user-images.githubusercontent.com/10572916/208821310-8733a325-761a-4c51-9621-1fbd57b22adc.png">

click on configure button in the image

<img width="339" alt="image" src="https://user-images.githubusercontent.com/10572916/208821417-0ff800e8-3b15-47d2-8c86-977264c43ec4.png">

add your metro bundler address ( in my case i changed the bundler port because of McAfee yours can be localhost:8081)

Congrats!
you found your metro bundler with chrome debugger

<img width="650" alt="image" src="https://user-images.githubusercontent.com/10572916/208821623-0ee96b91-18b0-40ec-b86a-84e2950061d0.png">

so far everything already exist in react native website but it didn't work for me and still i didn't have the debugger

after one working day challenge this solution worked for me
right click on inspect item on right click menu to open the debugger in same page (brave://inspect/#devices)

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/10572916/208822294-3b4ab9dc-c1e9-487b-b21c-3e3942d7bcaf.png">

the Node Js icon pointed in the above image was my solution. click on it

you will see this this screen opened ( by default console tab is opened)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10572916/208822466-8cc0baca-91e6-4d36-b8b2-7959515a3405.png">

you can see your added port and address to the browser and can see your console logs here
still i have some issue with API calls and will work on that
but at least i can continue your project ( if still you cant's see the logs reload your simulator and it will work)

actually the reason is previously when we were debugging in chrome react native was opening the debugger in chrome v8 engine. but the Hermes engine using the installed Node JS engine on your computer for debug and that's the reason it doesn't working on chrome

**Comment by filhodoto** [comment]
@Saeid-Barzegar [solution](https://github.com/facebook/hermes/issues/842#issuecomment-1360853086) worked for me. 
Cheers

**Comment by mattbfb** [comment]
Just to keep this thread updated: a fix has been submitted (https://github.com/facebook/metro/commit/6690b393cc1812af02f8eb20853504f0a6188a83) that should appear in upcoming versions of React Native.

**Comment by mattbfb** [comment]
This is available in recent version of React Native. Applications using recent React Native builds (e.g. one created today using `npx react-native init`) will populate the file list shown in the original issue post.

**Comment by Lurtroxx** [comment]
@Saeid-Barzegar you are a saint! Thank you.
