### ISSUE TITLE
TypeError: Constructor Map requires 'new'

### ISSUE THREAD

**Issue by jedashford** [facebook/hermes#86]
We continue to get crashing hermes with 'TypeError: `Constructor` Map requires 'new''

```
2019-08-14 21:31:41.529 20478-20633/? E/unknown:ReactNative: TypeError: Constructor Map requires 'new'
    
    This error is located at:
        in Unknown
        in c
        in Apollo(Component)
        in c
        in Apollo(Apollo(Component))
        in Unknown
        in f
        in Apollo(Component)
        in Unknown
        in Unknown
        in h
        in A
        in RCTView
        in RCTView
        in c, js engine: hermes, stack:
```

Even after removing all 'extends map' references, looks like apollo dependency might be failing on hermes. I can't help but feel like we have some babel config wrong, but our project matches exactly with react native 0.60.5

![image](https://user-images.githubusercontent.com/4111055/63064097-e49af380-bebc-11e9-9c7a-3023083a3384.png)

**Comment by ljharb** [comment]
You haven't included the full class declaration in your code example?

**Comment by dulinriley** [comment]
This will happen in Hermes if you run the following JS through it on the command line:
```
var a = Map();
```
According to the latest draft of the spec ES 10/2019 Section 23.1.1:
"""
The Map constructor:
...
* is not intended to be called as a function and will throw an exception when called in that manner.
...
"""

It needs to be called with `new` like so:
```
var a = new Map();
```

It sounds like what's happening is that either Babel (the transpiler) or Apollo (the library) is emitting invalid JS.
If you can, try source-mapping the stack trace to your original source code, and see what babel
thinks is the source of the error. If the source line is in Apollo's code and it looks like they
just forgot a `new` expression, file an issue with Apollo and resolve it there.
If it points to something that was generated by Babel, file an issue on Babel.

**Comment by ljharb** [comment]
Another possibility is that it’s a Map subclass that isn’t properly calling super; it’d be good to see the whole code.

**Comment by alberto264** [comment]
it also produces the same error while trying to execute

```
internals.Map = class extends Map {
  

    slice() {

        return new internals.Map(this);
    }

    toString() {

        return Util.inspect(this);
    }
};
```

**Comment by ljharb** [comment]
Perhaps hermes' default constructor isn't `constructor(...args) { super(...args); }`?

**Comment by jedashford** [comment]
We removed every reference to extending map in our code base, but looks like maybe another dependency is extending map since we're still getting the errors. We've disabled hermes for now, but I'd like to help figure it out.

**Comment by avp** [comment]
I think I found the actual problem here. When the user tries to extend Map, Babel emits some code to wrap the extended class conditionalized on the following code:
```
function _isNativeFunction(fn) {
  return Function.toString.call(fn).indexOf('[native code]') !== -1;
}
```

Hermes doesn't have the string `[native code]` but rather the string `[ native code ]`. As such, `Map` doesn't get wrapped properly when extended, and it is not called with `new` when subclasses construct it.

Babel REPL link: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAsgnlIAcIF4IGMA2IDO2IFMAPAF3wDsATPeJAbwCgBfe-s_Ad2jkQAoBKIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=true&targets=&version=7.5.5&externalPlugins=

d5ad9beaf66e7972e316f3de1c8c8c9b355865b5 updates the Function toString representation to use `[native code]` instead. This should fix your issue in the next release.

**Comment by vi5hnuu** [comment]
Is the  issue resolved.... bacause i am still getting the same error.

**Comment by tmikov** [comment]
@vi5hnuu AFAICT, the problem occurs when subclassing builtin classes using an ES6 transpiler. The problematic transpilation cannot be fixed in Hermes. However the next major of Hermes will support ES6 classes, so transpilation won't be necessary.
