### ISSUE TITLE
Syntax compilation errors lack adequate useful info

### ISSUE THREAD

**Issue by ariccio** [facebook/hermes#877]
## Bug Description

Syntax compilation errors (which are themselves NOT a hermes bug) appear to produce output intended for bytecode debugging, not syntax debugging:
```
HermesVM: Compiling JS failed: 1200:21:')' expected at end of function call,  Buffer size 7031284 starts with: 766172205f5f42554e444c455f535441 and has protection mode(s): r--p
```

The above is an error I encountered when I made a mistake and used `await` outside of an awaitable context.

The code that emits this error is here: https://github.com/facebook/hermes/blob/89dbdf5229e50bf0386ad0b0e564c83f61aad79d/API/hermes/hermes.cpp#L1480

The bugged version that metro delivered to hermes:
```
  console.log(await _reactNative.default.getTriggerNotifications());
```

and the corrected version: 

```
  _reactNative.default.getTriggerNotifications().then(function (result) {
    console.log(result);
  });
```

Simply displaying more of the invalid segment would save me minutes, [and other developers possibly hours](https://stackoverflow.com/questions/72104175/compiling-js-failed-react-native-expected-buffer-size).

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC
(pls don't make me do that?)

Hermes version: 0.70.5
React Native version (if any): 0.70.5
OS version (if any): Android 12
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

1. Break your code by using await outside of an awaitable context, in an expo bare/react-native app. I did this in a global context.
2. Run development mode on android.

code example:
```
  console.log(await _reactNative.default.getTriggerNotifications());
```

## The Expected Behavior
```
HermesVM: Compiling JS failed: 1200:21:')' expected at end of function call,  Buffer size 7031284 starts with: 766172205f5f42554e444c455f535441 and has protection mode(s): r--p
HermesVM: Failing JS expression excerpt: `console.log(await _reactNative.default.getTriggerNotifications());`
```

**Comment by tmikov** [comment]
I am sorry, I don't understand what the problem is. Per your own description, Hermes is generating the following error message "HermesVM: Compiling JS failed: 1200:21:')' expected at end of function call". What is wrong with that message? The additional information after the comma ("Buffer size...") can be ignored.

**Comment by ariccio** [comment]
Ah! Lemme go back and check to see why I didn't get that!

**Comment by ariccio** [comment]
Ok, so I'm not familiar enough with the hermes/jsi infrastructure to know for sure what's going on, but here's what I think I've found after poking around.

In this context, I'm not invoking hermes from the command line, it's being invoked somewhere in the depths of the react-native runtime.  I can only tell that the error was in hermes because `Compiling JS failed: 1200:21:')' expected at end of function call` made it through to the device log, accessed via `adb logcat`.

It appears that `LOG_EXCEPTION_CAUSE` is logging to the system log in addition to stderr, via [`__android_log_vprint`](https://github.com/facebook/hermes/blob/c2cd9e385a922f486a55e6bd70db2032f78379ed/lib/Platform/Logging.cpp#L27).

I suspect, but cannot tell for sure, that the useful error message is being output somewhere via stream to `llvh::outs`, like [here](https://github.com/facebook/hermes/blob/0c625b71bbbabf4b8e611adecdd57edd17403dbc/tools/jsi/jsi.cpp#L114), but not to the system log. It's not in the log, I checked.

I am not sure whether you consider this in the scope of a hermes problem/bug. It's an entirely reasonable design choice to *not* normally mirror stdout to the system log. For my use case, I'm not sure I have reasonable access to stdout. I don't even know where stdout goes on android! It does not seem to come through to my connected debug session (as invoked by `npx expo run:android --device`).

I think react-native may not even be invoking hermes as a subprocess, instead maybe calling in directly as a C++ API? ABI-compatibility would then explain why I have to compile hermes locally to use it?

Either way, it would be more useful to us downstream consumers of hermes if it did make it through to the system log!

Thanks for even looking at bug reports on a Friday night :)

**Comment by tmikov** [comment]
I see, so the problem is that in your use case the compilation error message isn't surfaced appropriately by the React Native infra. 

Let me give you some background: Hermes is first and foremost an ahead of time compiler. It is intended to be used on the command line (similar to a C++ compiler), where it consumes JavaScript and outputs bytecode. The compilation can take a bit of time. That is what is supposed to happen when you create a *release* (production) build of your RN app. Of course, eve then you are not invoking it directly, but it is being invoked as a subprocess by a script or something.

In development mode, Metro sends source directly to the device and the RN integration code uses JSI to execute it directly. This is not an optimal case for Hermes, which, as I mentioned, is primarily an AOT compiler. Using it to run source directly produces inefficient and slower code, but it enables a more interactive development experience.

So, I am assuming you are in the second case, that's why you are seeing the error in the device log. My guess is that the RN infra doesn't expect that there would be syntax errors in the source, since the source passes through Babel first, which should have caught all errors. So, this behavior is not that surprising. But why aren't you getting an error from Babel?

As an experiment, can you try creating a release build of your app?

I apologize for any inaccuracies above. We on the Hermes team are actually not very familiar with RN and the integration, since our focus is the compiler and the VM. You are likely to get much better help if you submit an issue to React Native (especially since this is clearly not a Hermes bug).

I am curious though about what is going on, so if you create a RN issue, please link it here (or perhaps Github will auto-link it, if you mention this issue in the new one).

**Comment by ariccio** [comment]
> So, I am assuming you are in the second case, that's why you are seeing the error in the device log. My guess is that the RN infra doesn't expect that there would be syntax errors in the source, since the source passes through Babel first, which should have caught all errors. So, this behavior is not that surprising. But why aren't you getting an error from Babel?

I was wondering this myself. I'd noticed that I don't get any warnings through expo, which is way less than ideal, but I chocked that up to just another mysterious issue in the larger expo/react-native build systems, which is [wildly flaky](https://github.com/ariccio/COVID-CO2-tracker/commit/302b96d35c813158c6175d53455a48e420151d62) in my experience. I'm definitely a lot less OCD when it comes to javascript build warnings than C++. This will definitely take a bit of poking!


> (EDIT: to clarify. When used as an API, Hermes correctly produces the error and passes it to RN. When RN does with it is really outside of the scope of Hermes. Sure, Hermes logs it, but that's just for debugging, that's not supposed to be how errors are reported)
>
> As an experiment, can you try creating a release build of your app?

Yup, spot on. All works correctly here.

```
info Writing bundle output to:, /Users/alexanderriccio/Documents/GitHub/COVID-CO2-tracker/co2_native_client/android/app/build/generated/assets/react/release/index.android.bundle
info Writing sourcemap output to:, /Users/alexanderriccio/Documents/GitHub/COVID-CO2-tracker/co2_native_client/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
info Done writing sourcemap output
info Done writing bundle output
/Users/alexanderriccio/Documents/GitHub/COVID-CO2-tracker/co2_native_client/android/app/build/generated/assets/react/release/index.android.bundle:712:21: error: ')' expected at end of function call
  console.log(await _reactNative.default.getTriggerNotifications());
             ~~~~~~~^

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/Users/alexanderriccio/Documents/GitHub/COVID-CO2-tracker/co2_native_client/node_modules/react-native/react.gradle' line: 286

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command '/Users/alexanderriccio/Documents/GitHub/COVID-CO2-tracker/co2_native_client/node_modules/react-native/sdks/hermesc/osx-bin/hermesc'' finished with non-zero exit value 2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

```

> I am curious though about what is going on, so if you create a RN issue, please link it here (or perhaps Github will auto-link it, if you mention this issue in the new one).

I definitely will! Filing and investigating little things like this can take hours ...but I say to myself that if everybody who ever encountered these weird little problems did the same, we'd all have a more pleasant development experience 😊

I appreciate your time for what turns out to not be a Hermes-fixable bug.

The issue should definitely auto-link-back if I mention it. I do it all the time, I find it super useful for the next person to come along and piece things together. So closing this with comment.

**Comment by ariccio** [comment]
In case you don't get a notification, this comment will do it. What a bizarre bug! Enjoy your holidays :)

**Comment by tmikov** [comment]
Very interesting. One working theory is that Babel didn't transpile the await because it didn't look like a valid await. So, it was left unchanged and it reached Hermes. 

Another interesting detail is that Hermes itself actually supports async/await natively, so they don't need to be transpiled, but apparently that transform is still enabled. I wonder why?
