### ISSUE TITLE
Support regex named capture groups

### ISSUE THREAD

**Issue by Sam-Martin** [facebook/hermes#89]
It looks like the regex parser doesn't currently support named capture groups.
If you specify one, e.g. 
```
regex = new RegExp('(?<contextBefore>.*)', 'ig')
```
 it will throw a `SyntaxError: Invalid RegExp patterm: Quantifier has nothing to repeat, js engine: hermes`
Is this intentional, or a bug?

**Comment by mhorowitz** [comment]
It's intentional.  The list of features we target today is based on ES6 (the 2015 edition of the language specification): https://github.com/facebook/hermes/blob/master/doc/Features.md

Named capture groups were [added in the 2018 edition](https://www.ecma-international.org/ecma-262/9.0/#sec-intro).  We expect to support newer versions of the spec, including this feature, in the future, but we don't have a roadmap for this yet.

**Comment by bombillazo** [comment]
Hello, could this feature be considered for the hermes roadmap?

As more dependencies and libraries start incorporating named capture groups into their code, hermes will break the app building process when it finds those deps. It is already occurring as discussed in chalk/ansi-styles#78 and chalk/ansi-styles#80.

Thanks.
