### ISSUE TITLE
Can Hermes support RAM bundling ?

### ISSUE THREAD

**Issue by RajeshBatth** [facebook/hermes#93]
Can hermes support RAM bundle format, this can further improve performance when the bundle size is too big (> 10MB)?

**Comment by RajeshBatth** [comment]
Thanks @avp 
Just one more question: **Can we load multiple hermes' bundles in a single VM?**
I'm implementing my own code-push solution, where I want load one base-bundle(vendor dependencies like RN) and multiple module-bundles(module can a feature-set) on demand, with this I can update individual module-bundles.

**Comment by pke** [comment]
But the general principles of delaying loading/importing of files still apply with hermes?

**Comment by johnculviner** [comment]
I'm curious if there has been anymore thought on this. There is not zero cost associated with hermes bundle size as I can illustrate here:

I have an application with a few examples:

Case A - hermes bundle is 1.7MB - in test situation
Case B - hermes bundle is 10.8MB - normally

The app is 2s slower to load in case B even though I'm not actually rendering anything different on the screen. The difference is commenting out the entry point into the rest of the app structure causing it to be tree shaken away in case B.

If I could delay part of the load of B till later I would expect app start time to go down.

**Comment by tmikov** [comment]
@johnculviner it is unlikely that the size of the bundle is causing a slowdown, I suspect that the difference is that in Case A you are running a lot less initialization code.

**Comment by sriharshaarangi** [comment]
I was looking at memory usage rather than latency, and I have similar observations as @johnculviner. While there is no difference in what I'm rendering on screen, the memory used (pss) keeps getting higher with bundle size. I was progressively increasing bundle size by adding dependencies which are used in screens other than the home/main screen). And if I comment out those dependency usages in typescript code, again as @johnculviner, they are getting tree shaken away, and both the memory used is getting back along with bundle size and APK size.

**Comment by tmikov** [comment]
@sriharshaarangi I am not sure what the problem is. Do you expect running a larger bundle to consume the same amount of memory as a smaller bundle? 

Hermes bytecode bundles are intended to be memory mapped (of course whether that is actually the case is up to the integrator). So, pages in the bundle are loaded into memory the first time they are executed. The more stuff you execute, the more stuff gets into memory and PSS increases. 

The significant advantage compared to any other approach is that the bundle is loaded truly lazily only when parts of it are actually touched. Additionally, if it is a read-only memory mapping, the OS can release parts of the consumed memory if it needs to and automatically page them in later again. This is exactly the same mechanism used by native shared libraries.

**Comment by sriharshaarangi** [comment]
Apologies if I was not clear, I will try expanding the scenario. 

I have

**Comment by sriharshaarangi** [comment]
Apologies if I was not clear, I will try expanding the scenario.

I have 2 separate apps: 

App "A" is just the default react native hello world app. Let us call it Screen 1. 
App "B" has 2 copies of the hello world screen. First copy(Screen 1) is as is and unmodified - identical to hello world screen in App "A". Second copy (Screen 2) uses additional components from new dependencies like React-native-paper, gluestack. Screen 2 is a separate RN root component  and loaded as part of a different android activity altogether. index.js snippet for the same:

```
AppRegistry.registerComponent(screenName1, () => Screen1);
AppRegistry.registerComponent(screenName2, () => Screen2);
```

Now, we are trying to compare memory used by App "A" vs App "B" when launching Screen 1. Since the code executed is ~identical in both apps, I expect it to be roughly the same. However, the memory used by the App "B" when launching Screen 1 is proportionally increasing with dependencies I am adding to Screen 2 which we are not launching. I did not expect this behaviour as per my understanding of how hermes loads bytecode.

Moreover, I have attempted wrapping the new library dependencies in Screen 2 to inline requires(https://reactnative.dev/docs/ram-bundles-inline-requires) to see if the dynamic import with require helps in not loading the unnecessary bytecode to memory. However, the memory used was still same as with static imports.

The numbers we have (RN 72 version): 
App "A": FG PSS memory: ~50-52 MB, APK size: 7.6 MB
App "B", when launching "Screen 1", FG PSS memory: ~60 MB, APK size: ~8.6 MB. (Screen 2 has text and button components from Gluestack and React-native-paper libraries. the increase in APK/bundle size is these additional dependencies)
 
I deduce @johnculviner is also referring to very similar scenario from his above comment, though he was measuring latency.

Hope this clarifies!

**Comment by tmikov** [comment]
@sriharshaarangi Hermes only touches code in the bundle when it executes it, so unless something is executed, it won't be loaded in memory. But we don't control how the application is organized or how a packager handles the imports and produces a bundle.

You are correct that with static imports all dependencies are transitively initialized at the start, consuming memory that you don't necessarily need right away. "inline requires" are indeed able to address this. Unfortunately the Hermes team can't really help with packager configuration, etc. We only understand the VM itself.

My advice is to figure out how to see track modules are initialized and when (the link you posted seems to indicate that there is a way) and make sure that the additional modules truly are not being initialized until needed.

You also need to consider that differences of only a few MB are not necessarily attributable to one specific thing - there is GC activity, metadata, etc. You should consider experimenting with a truly huge JS module (it can be code generated) that is never used.

**Comment by sriharshaarangi** [comment]
I did as suggested above. Removed external dependencies, generated a huge component (10 MB in size), and repeated the experiment. 

As per this [code](https://reactnative.dev/docs/ram-bundles-inline-requires#investigating-the-loaded-modules), the additional module (containing 10 MB component) were not getting loaded when doing dynamic import (either via `require` or via `import()`), while it was getting loaded when doing static import. However, memory used remained the same in both the static and dynamic cases (~71 MB), and was much higher than without component case (~53 MB)! 

Investigated the increase in 18 MB by using `adb shell dumpsys meminfo`. The increase came from .apk mmap (+8 MB) and native heap (+10 MB). So the entire bundle still seems to be getting loaded and processed even in case of dynamic imports. 

I will share the reproducible example tomorrow on this thread. So in case I am doing something incorrect, you can point it out.

**Comment by tmikov** [comment]
@sriharshaarangi I ran some tests to confirm that the bundle is not loaded in memory unless executed. I have uploaded two files:
- [small.js](https://gist.github.com/tmikov/fbcadcf80621c0cdf0a95d0d64d30ff4)
- [large.js](https://gist.github.com/tmikov/67ea5a5b3b080ed9d97176ee85219e2e)

You can compile either one by running (replace `xxx` with the file name):
```sh
hermes -O0 -emit-binary -out xxx.hbc xxx.js
```
`small.js` produces a 767 byte bundle, while `large.js` produces 9.8 MB.

Then we can run the small one to establish a baseline for RSS with a very small bundle on your host platform (MacOS or Linux):
```sh
 hermes --gc-print-stats small.hbc 2>&1 | grep "Peak RSS"
```

On my Linux host (which is closest to Android) I get:
```sh
$ hermes --gc-print-stats small.hbc 2>&1 | grep "Peak RSS"
    "Peak RSS": 15372288,
```

So, about 15MB for a minimal bundle.

Then we can tweak the beginning of the large bundle with a text editor and set it to **not touch** the large code:
```JavaScript
var run = false; // Setting this to false does not run the large code
var ratio = 0.5;
```
Compile it to bytecode as described above and run it. On my system I get:
```sh
$ hermes --gc-print-stats large.hbc 2>&1 | grep "Peak RSS"
    "Peak RSS": 15372288,
```

As you can see, running the large bundle consumes the same amount of memory as the small one (15 MB) because we aren't actually executing the large amount of code.

Then we edit `large.js` and change it to run the entire bundle:
```JavaScript
var run = true; // Setting this to true runs the large code
var ratio = 1; // Setting this to 1 causes it to run all of the code.
```

Compile it to bytecode as described above and run it. On my system I get:
```sh
$ hermes --gc-print-stats large.hbc 2>&1 | grep "Peak RSS"
    "Peak RSS": 25116672,
```
It consumed 9.3 MB of additional memory, which is about the size of the large bundle.

If this isn't enough evidence that we only consume memory for what we run, let's edit `large.js` again:
```JavaScript
var run = true; // Setting this to true runs the large code
var ratio = 0.5; // Setting this to 0.5 causes it to run half of the code.
```

Compile it to bytecode as described above and run it. On my system I get:
```sh
$ hermes --gc-print-stats large.hbc 2>&1 | grep "Peak RSS"
    "Peak RSS": 19177472,
```
It consumed 3.6 MB of additional memory.

Feel free to play with `ratio` and examine RSS, you will see how they correspond to each other.

There is absolutely no doubt that Hermes works in the way that it is intended to. However various problems can be caused by integration or bundle packaging.

**Comment by sriharshaarangi** [comment]
Thank you for the detailed example, appreciate it! 

> However various problems can be caused by integration or bundle packaging.

True, this may likely be the cause. I have followed the react native documentation to set up the sample app. Hermes is enabled by default. I did not come across any documentation which says I need to update a config to get the memory/latency benefits, apart from inline requires which I already enabled. Unless I did something incorrect, if the default hermes config in RN is not optimised for it, then many react native developers may not be realising the benefits that hermes has to offer.

Here is the repo containing the code I am testing with - https://github.com/sriharshaarangi/RNExperiments/commits/main/. Maybe it has to do with React Native than hermes, but at least I don't see anything obvious I am missing. In case if you find something, please let me know, thank you!

**Comment by tmikov** [comment]
@sriharshaarangi can you share the unminified packaged bundle as JS before it is compiled to bytecode? (I don't know how to do that, but it must be possible). We should be able to tell whether code is "touched" unnecessarily.

**Comment by martinbigio** [comment]
You can generate the unminified version with the following command.

```
npx react-native bundle \                                           
  --dev true \
  --platform android \
  --entry-file index.js \
  --bundle-output bundle.dev.js
```

If you were able to repro this on a minimal RN app and you could share a zip file with it, that may help too. Thx!

**Comment by sriharshaarangi** [comment]
Here is the compressed bundle.dev.js - [bundle.dev.js.zip](https://github.com/facebook/hermes/files/14892266/bundle.dev.js.zip)

> If you were able to repro this on a minimal RN app and you could share a zip file with it, that may help too. Thx!

Here is the repo https://github.com/sriharshaarangi/RNExperiments/commits/main/ shared above for the same.

**Comment by martinbigio** [comment]
Here is the unminified (dev) bundle: https://gist.github.com/martinbigio/d9e5d79b34a7a590581f6fee4539df1c.

I don't see anything suspicious in it: The `LargeComponent` factory method is indeed not executed on start up because of the indirection introduced with `LargeComponentWrapper` and the fact that doing `AppRegistry.registerComponent` doesn't invoke said factory method.

**Comment by martinbigio** [comment]
@tmikov I assume strings are not allocated eagerly on the global string table, but if they do, that would explain why on the repro case we're seeing memory increase. The "LargeComponent" variant mostly has strings.

**Comment by martinbigio** [comment]
I modified the repro to return a View containing 100,000 Text components but all with the same string rather than different ones. Building the app in release mode and looking at RSS I get the following results:
- LargeComponent included on bundle (baseline): 53MB
- LargeComponent (not loaded) with different values for each text string 71MB
- LargeComponent (not loaded) with all text strings identical: 53MB Large

For reference, the LargeComponent is represented on the bundle this way: https://gist.github.com/martinbigio/7f2e8c0f87255e1eb822a881bee3cee2

I haven't been able to create a standalone repro that doesn't require RN yet..

**Comment by tmikov** [comment]
@martinbigio string literal constants are allocated lazily the first time they are used. Property names are allocated either eagerly or lazily depending on whether `RuntimeModuleFlags::persistent` is set. It is always set by JSI, so they are always lazy (but even if they weren't, property names should occupy negligible space). 

Of course, there is additional metadata associated with more strings and more functions, so not everything is completely lazy, there is always some amount of work and memory allocation that is performed eagerly, but it should be small relative to the remaining lazy one.

**Comment by sriharshaarangi** [comment]
Thank you both for taking time to investigate this! While I was using the LargeComponent that was synthetically generated, I was observing same behaviour if I replace LargeComponent with say a Text component from UI library like react-native-paper/gluestack, the memory goes up. While I understand we cannot expect 0 memory change when adding new dependency, it remains the same irrespective of whether we are statically importing it or requiring it inline, which leads me to the similar conclusion that even though the module is not initialised, the entire bundle seems to be actually being loaded into memory. 

I will add more commits to above repo, compare the numbers and share them here. 

First commit to replace the huge text blocks in LargeComponent with a Text component from 1 UI library, and then measure memory with and without dynamic import of LargeComponent. Now introduce another Text component from another UI library, and then measure the same, to see the incremental increase.

**Comment by sriharshaarangi** [comment]
Still the same observations as I initially called out. I don't see any difference in memory measurements between dynamic require and static import. And for each 1 MB of bundle size increase (uncompressed), there seems to be roughly 2 MB impact on pss memory, even if those components are not actually used/rendered on screen.

Pushed the changes to https://github.com/sriharshaarangi/RNExperiments/commits/main/

(commands assume we are at the root of workspace/repo):
Command to generate APK: `react-native run-android --variant=release`
Command to measure bundle size after APK is built successfully: `ls -l android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle`
command 
Command to measure APK size: `ls -l android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk`

|                                                                                                   | APK size | Bundle size (uncompressed) | Memory pss |   |
|---------------------------------------------------------------------------------------------------|----------|----------------------------|------------|---|
| Hello world                                                                                       | 7.59 MB  | 0.77 MB                    | 51.5 MB    |   |
| Hello world with RN paper component (Both dynamic require and static import cases)                | 7.86 MB  | 1.27 MB                    | 53 MB      |   |
| Hello world with RN paper and gluestack components (Both dynamic require and static import cases) | 8.59 MB  | 2.67 MB                    | 57 MB      |   |

**Comment by sriharshaarangi** [comment]
I have copied the [large.js in above comment](https://github.com/facebook/hermes/issues/93#issuecomment-2038586674) into the hello world react native app. Even with `run=true`, bundle and APK size have not increased by more than 0.01 MB. It is likely due to bytecode being optimised.

Please find the commit for the same - https://github.com/sriharshaarangi/RNExperiments/commit/25d556073fd5883640b825b7a4e7750da12190d6

|                                                                                                   | APK size | Memory pss | 
|---------------------------------------------------------------------------------------------------|----------|----------------------------|
| Hello world (proguard enabled)                                                                                       | 6.02 MB  | 50 - 51 MB    | 
| Hello world with large component (proguard enabled), `run=false`  | 6.02 MB  | 50 - 51 MB     | 
|  Hello world with large component (proguard enabled), `run=false` | 6.03 MB  | 50 - 51 MB     |

**Comment by sriharshaarangi** [comment]
Apart from the memory used, another way to check whether the unused code has loaded is by splitting bundles. RAM bundles is not supported with hermes and metro bundler does not have required documentation on achieving split bundles. 

However, Re.pack bundler supports that. Hence I have switched to Re.pack bundler and attempted `dynamic import()` with lazy loading for the `LargeComponent`. Surprisingly, memory used was same as without `LargeComponent` case (~53 MB)! So hermes is not actually touching the code in case the lazily loaded component is part of a separate bundle.

In case of Metro bundler with single bundle, even though hermes is not touching the code, something else should be causing the bundle to be loaded into memory (hence using 71 MB instead of the expected 53 MB). Maybe someone from RN Android team should be looking into this.

Code can be found here - https://github.com/sriharshaarangi/RNExperiments/commits/large_component, where initially it was using metro bundler. Later, we switching it to Re.pack with code splitting.

**Comment by sriharshaarangi** [comment]
One hypothesis I have is that the bundle is in a compressed form inside the APK. Since the uncompressed bundle is not stored to disk anywhere, on every cold start it is uncompressed in the memory before it can be executed.

Android [had a similar problem](https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs) with native libraries (.so files), and then they started having a flag to have the uncompressed .so files in APK, to avoid the double storage impact of the .so files. Prior to that, all the native libraries would be extracted to libs folder in app's private storage at the time of installation.

**Comment by sriharshaarangi** [comment]
@tmikov I did not see any bundle in `/data/data/<package_name>/` directory or its sub-directories. Could not find any documentation either that bundle would be uncompressed and cached on disk.
