### ISSUE TITLE
Native Debug Symbol for RN 0.71.4 missing

### ISSUE THREAD

**Issue by gfrancischini** [facebook/hermes#944]
Hi, how can we get native debug symbols for version 0.71.4 to follow this steps? 

https://hermesengine.dev/docs/react-native-integration#reporting-native-crashes

Thanks

**Comment by newobj** [comment]
Hi there,

Unfortunately this documentation is now out of date, due to RN changing how Hermes is bundled. We'll work to update the documentation. RN now gets Hermes from Maven, and in the Maven repo you'll find .aar's which contain the Hermes binaries:

https://repo1.maven.org/maven2/com/facebook/react/hermes-android/0.71.4/

If you look inside `hermes-android-0.71.4-release.aar`, you'll find a directory `prefab\modules\libhermes\libs`prefab\modules\libhermes\libs` which has unstripped libraries for the various platforms.

**Comment by gfrancischini** [comment]
Thanks for the update.
