### ISSUE TITLE
Wrong output of lambda expression

### ISSUE THREAD

**Issue by Georgezxh** [facebook/hermes#953]
Hermes version:0.12.0
OS version (if any):ubuntu20.04
## Bug Description

When I run the following code, hermes prints a different result than the other js engines. Is it because hermes doesn't support lambda expression?

code example:
var fn = foo => { foo(); }
print(fn);

## Output
function fn(a0) { [bytecode] }

## The Expected Behavior
foo => { foo(); }

**Comment by jpporto** [comment]
No, this is because ecma 262 does not require [String.prototype.toString](https://tc39.es/ecma262/#sec-function.prototype.tostring) to print the function source code. In particular:

> 4. If func [is an Object](https://tc39.es/ecma262/#sec-object-type) and [IsCallable](https://tc39.es/ecma262/#sec-iscallable)(func) is true, return an [implementation-defined](https://tc39.es/ecma262/#implementation-defined) String source code representation of func. The representation must have the syntax of a [NativeFunction](https://tc39.es/ecma262/#prod-NativeFunction).

Hermes works by compiling JavaScript down to bytecode before execution, thus source code is not available to the engine when the JS code is running. Use can use hermes' ```"show source"``` directive if you want to see the function's source code during execution:

```
>> print(_ => {})
function (a0) { [bytecode] }
>> print(_ => {"show source"})
_ => {"show source"}
```
