### ISSUE TITLE
Cannot read property 'duration' of null

### ISSUE THREAD

**Issue by serzmerz** [facebook/hermes#99]
```Keyboard.addListener('keyboardDidHide', callback);```
In callback must be exist first param KeyboardEvent, but i have null instead.

**Comment by avp** [comment]
It would be helpful to have more information so that we can debug this with you.

To help reproduce this, can you please upload a minimal JS bundle which demonstrates the error when run with Hermes? For example, a file `bundle.js` which when run with Hermes using `./hermes bundle.js` throws the error.

Alternately, you can put a small React Native project on GitHub which shows the issue when running Hermes on your Android phone and we can try and reproduce from there.
